validators/ethereum/rpc-tests/makechain.js

Currently the `makechain.js` create block files for the rpc-tests in an asynchronous matter. This has several problems:
1. the blocks directory might not been created, and writing block files into that directory can fail
2. the nodejs script can exit while not all files have been written since no callback is given for the `writeFile` method
This PR will do everything synchronously. This ensures all block files are written before the nodejs script exits.

rpc-test: create block files for import synchronous

---

README.md
clients/go-ethereum:develop/geth.sh
clients/go-ethereum:local/geth.sh
clients/go-ethereum:master/geth.sh
containers.go

This PR adds support for custom keystore directories for nodes.
I would like to start multiple nodes with their own set of keys that have preallocated amounts of ether in the genesis block. This PR will copy all subdirectories/files from `/keystore` into the node container. It also introduces a new variable that can be used to specify a custom keystore.
Example usage:
Create the keystore directories in the docker file:
```
RUN mkdir -p /keystore/1 /keystore/2 /keystore/3 /keystore/4
ADD 87da6a8c6e9eff15d703fc2773e32f6af8dbe301 /keystore/1/
ADD 0161e041aad467a890839d5b08b138c1e6373072 /keystore/2/
ADD b97de4b8c857e4f6bc354f226dc3249aaee49209 /keystore/3/
ADD cf49fda3be353c69b41ed96333cd24302da4556f /keystore/4/
```
Start the nodes in the simulator script with a custom keystore directory: …

hive: add support for custom keystore location

---

clients/parity:beta/parity.sh
clients/parity:master/parity.sh
clients/parity:stable/parity.sh

Parity [no longer](https://github.com/ethcore/parity/commit/744501c45460098be5ad41d9b7783c84fc92a0d4#diff-a446157098e33897a7686a206229874a) supports the --no-network flag.

update parity flag --no-network to --nodiscover

---

clients/go-ethereum:develop/Dockerfile
clients/go-ethereum:master/Dockerfile
clients/parity:beta/Dockerfile
clients/parity:master/Dockerfile
clients/parity:stable/Dockerfile

This PR organises the Dockerfiles so that the docker cache is better reused between clients. Basically: 
- Fetch all general utilities and update package repositories 
- Check out the relevant github repo
- For parity: `cargo fetch` to download most of the dependencies
The steps above are cached by docker after the first client has been built. Afterwards, the remaining non-cached steps are
- Check out correct branch
- Build
This shaves a lot of times off the build times for the docker images
See https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/build-cache

Refactored the Dockerfiles

---

README.md
clients/go-ethereum:local/geth.sh
clients/go-ethereum:master/geth.sh
clients/go-ethereum:metro/Dockerfile
clients/go-ethereum:metro/geth.sh
clients/go-ethereum:stable/geth.sh
clients/parity:beta/Dockerfile
clients/parity:beta/chain.json
clients/parity:beta/parity.sh
clients/parity:master/Dockerfile
clients/parity:master/chain.json
clients/parity:master/parity.sh
clients/parity:stable/Dockerfile
clients/parity:stable/chain.json
clients/parity:stable/parity.sh
simulators/ethereum/consensus/hivemodel.py
simulators/ethereum/consensus/testmodel.py

Fixes in this PR
* Parity changed repo to 'paritytech', thus dockerfiles stopped working
* Geth's new (and grumpy) json-parsing, requires us to rewrite various fields in genesis
* Skips tests which contain invalid hex; specifically the "invalid rlp"-tests which cannot be converted into binary, thus impossible to execute. 
* Added config for Metropolis, both Geth and Parity (parity tests use Metro-rules unless this is included, so tests fail)
* Defined `Metropolis` network, which the ethereum tests use. 
* Fixes a bash-error in the metropolis integration, and adds the metro-geth from @obscuren. 
Supersedes https://github.com/karalabe/hive/pull/41

Metropolis, geth-fixes, parity-fixes

---

simulators/ethereum/consensus/hivemodel.py
simulators/ethereum/consensus/simulator.py
simulators/ethereum/consensus/testmodel.py

The killNode() method was not wrapped in a try/except, so if it raised
any exception it'd cause the whole simulator to crash.
Also refactors some code in hivemodel.py to make it simpler and easier
to follow.

simulators/consensus: do not crash if fails to kill a node

---

simulators/ethereum/consensus/hivemodel.py

If newNode() raises an exception we were recording a test failure and
moving on, eventually trying to use its return value (to kill the node)
and crashing with an UnboundLocalError because the variable was
referenced before assignment. Now we record the test failure and exit
early.

simulators/consensus: do not crash when newNode() fails

---

simulators/ethereum/consensus/hivemodel.py
simulators/ethereum/consensus/simulator.py

Now HiveAPI only deals with talking to the node running the simulator API,
and BlockTestExecutor uses is passed a HiveAPI instance so that it can do
its job
This also fixes a bug I accidentally introduced in a recent change: BlockTestExecutor was referencing a self.hive attribute which no longer existed.

simulators/consensus: Refactor HiveAPI/BlockTestExecutor

---

simulators/ethereum/consensus/hivemodel.py
simulators/ethereum/consensus/simulator.py
simulators/ethereum/consensus/testmodel.py

The tests have now been changed, to not use hardcoded folders but instead that each test has a `network` configuration. This means that we don't have to infer rules from the folder, but can scan the test repo for tests in all folders recursively.

Remove hardcoded folders, as tests now are configured with network

---

README.md

Some example commands in `README.md` uses the removed branch `go-ethereum:develop`.  This PR replaces that with a branch that exists.

go-ethereum:develop does not exist anymore, so change the examples

---

clients/parity:master/chain.json
clients/parity:master/parity.sh
simulators/ethereum/consensus/hivemodel.py

Update parity configuration (https://github.com/karalabe/hive/issues/67) , also fix some strange issue where `traceback` does not properly function within a multithreaded setting.

Parity fixes

---

simulators/ethereum/consensus/hivemodel.py

Skip Constantinople cases since they are guaranteed to show up as failures on [hivetests](http://hivetests.ethstats.net/) for clients that are only targeting Byzantium.

skip constantinople tests in consensus runner

---

clients/cpp-ethereum:develop/config.json

typo fixed in https://github.com/ethereum/cpp-ethereum/pull/4434

fix typo for cpp homestead config

---

clients/cpp-ethereum:develop/eth.sh

Avoid passing unsupported genesis fields to cpp-ethereum

---

clients/ethereumj:develop/Dockerfile
clients/ethereumj:master/harmony.sh

ethereumj:develop was not fully built on built stage in Dockerfile, so it downloaded dependencies on every test. I've fixed it. Should resolve #88

Fixed ethereumj:develop client to be fully built in Dockerfile

---

clients/ethereumj:develop/Dockerfile
clients/ethereumj:local/Dockerfile
clients/ethereumj:master/Dockerfile

@holiman this should fix #95 
This image is based on alpine, so it's lightweight too, but Oracle often updates JDK download url, so old one stops to work. This docker image looks well-maintained, so we will use it. Another approach is to use Ubuntu, it has normal java installer, but it's not light like alpine, so we'd try this one.

Fixed Java install for EthereumJ client

---

clients/parity:master/parity.sh

Fixes error caused when parity moved the `maxCodeSizeTransition` as a parameter into the chain config in https://github.com/paritytech/parity/pull/8067 .

Fix for https://github.com/paritytech/parity/pull/8067

---

clients/parity:master/chain.json
clients/parity:master/parity.sh

Parity needs to have defaults for fork numbers, otherwise it becomes `0`.

set parity fork numbers to very high (otherwise defaults to 0)

---

clients/aleth:nightly/aleth.sh
clients/parity:beta/parity.sh
clients/parity:master/parity.sh

As per https://github.com/karalabe/hive/issues/113
This PR so far adds
@chfast, could you help out with the aleth configs? 
@folsen, could you help out with what to use for skinny create 2 ?

Add constantinople configs

---

hive.go
images.go

Correcting issue 111 (https://github.com/karalabe/hive/issues/111). Issue corrected by creating buildError type to pass client information back to calling function. This type is then used to construct the json output as requested.

Fixing Issue 111: Add json output of build error

---

clients/parity:master/chain.json
clients/parity:master/parity.sh

Handle https://github.com/paritytech/parity-ethereum/pull/9480: 
- Remove eip649 references, and has a list of blockRewards

Parity config update

---

hive.go
simulators/ethereum/consensus/hivemodel.py

The call to `subresult` was missing one parameter, in the case that a node failed to start

Simulator fix, hive output fix

---

hive.go
simulator.go
simulators/common/simulator.go
simulators/devp2p/basic/devp2p_test.go
simulators/ethereum/consensus2/Dockerfile

This PR replaces the python-framework for consensus testing with a framework written in go. Additionally, it
* return ip when starting node
* surface http errors as golang erros in the simulator api client
* kills nodes when subresults are reported

Simulation work

---

containers.go

Skips some container-interaction when a path is `ignore`, also fixes the copy-from-template to at least not be obviously br0ken

Make extra container for copying easier to avoid

---

README.md
chaintools/chaintools.go
chaintools/sealingEthash.go
hive.go
simulators/devp2p/basic/devp2p_test.go

This PR adds the "chain tools" (chaintools folder) necessary for the sync simulations. It also adds some helpful command line options to Hive to allow testers to generate rlp encoded blockchains for import. More info in the Readme.md.
In future PRs these chaintools may be moved to simulators/common to allow dynamic regeneration of blockchains for sync tests.

Chain tools

---

clients/go-ethereum_master/geth.sh

This PR makes the geth image invoke `jq` a total of two times, instead of ~9. Might make a little bit of difference speedwise

geth: less jq invocations

---

benchmarker.go
hive.go
simulator.go
validator.go

Fixes #178 by returning an error when given regexp does not match any clients.
Also fixes #175 because the error documented there is what happens when the sim tries to put logs in a path without a client path element.

Return error if no clients match given client regexp pattern

---

clients/go-ethereum_master/geth.sh

Was causing:
DBUG[03-05|13:25:54] starting container                       client=go-ethereum_master validator=smoke/genesis-chain-blocks id=b6ef6d4e
[b6ef6d4e] /geth.sh: line 66: [: : unary operator expected
[b6ef6d4e] Initializing database with genesis state...
[b6ef6d4e] WARN [03-05|19:26:19.326] Sanitizing cache to Go's GC limits       provided=1024 updated=666
[b6ef6d4e] INFO [03-05|19:26:19.327] Maximum peer count                       ETH=25 LES=0 total=25
[b6ef6d4e] INFO [03-05|19:26:19.328] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=16.00MiB handles=16
[b6ef6d4e] Fatal: Failed to write genesis block: genesis has no chain configuration
[b6ef6d4e] Fatal: Failed to write genesis block: genesis has no chain configuration

Fix typo in go-ethereum_master that breaks all tests for that client 

---

simulators/devp2p/udp.go
simulators/ethereum/sync/sync_test.go

Parity now behaves differently in response to FindNode in that replies with a Ping... the test needs to be extended to see if this is an error or not.
The sync tests were failing for Parity too, but this was down to an error in the sync test.

Test fixes

---

containers.go
hiveviewer/index.html

less verbosity
move testresults to `Results`, so we can have a symlink pointing to either the S3 bucket or a local folder

containers: don't write container stdout to stdout for loglevels below 4

---

clients/aleth/aleth.sh
clients/besu/besu.sh
clients/go-ethereum/geth.sh
clients/parity/parity.sh
hive.go
hiveviewer/Scripts/app/app.js
hiveviewer/index.html
hiveviewer/testsuite.html
hiveviewer/testsuitecomponent.html
simulator.go
simulators/common/providers/hive/hive.go
simulators/common/providers/local/local.go
simulators/common/providers/local/local_test.go
simulators/common/testmanager.go
simulators/common/testsuite.go
simulators/common/testsuiteprovider.go
simulators/common/utils.go
simulators/devp2p/basic/devp2p_test.go
simulators/devp2p/basic/tests.sh
simulators/devp2p/udp.go
simulators/ethereum/consensus/main.go
simulators/ethereum/consensus/tests.sh
simulators/ethereum/graphql/graphql.go
simulators/ethereum/graphql/graphql_test.go
simulators/ethereum/sync/sync_test.go
test.sh

A massive PR which brings along quite a lot of needed maintenance. To name a few: 
- Graphql tests now actually work (they previously failed, but were reported as successfull). Geth + Besu enabled. 
- Aleth fixed up for Istanbul+
- Ability to download simulator log file, which is quite important
- Expose log file even if client container doesn't open RPC port
- Several more cmd line options, e..g to make it possible to run tests more limited, for local testing
- Make "popups" use regular windows/tabs instead of pesky floating windows
Changes some cmd line params too: 
```
sim-parallelism => sim.parallelism
simlimiter => sim.testlimit
sim-rootcontext => sim.rootcontext
simloglevel => sim.loglevel
```

Make hive operational again

---

clients/aleth/enode.sh
clients/besu/besu.sh
clients/parity/enode.sh
clients/parity/parity.sh
simulators/ethereum/sync/sync_test.go

This PR changes the way the sync-tests behaves, to not be tied to geth, but any client syncing with any client. 
It uses the `HIVE_BOOTNODE` env variable instead of RPC peering. 
Also fixes the besu genesis problem in https://github.com/ethereum/hive/issues/259 .

refactor the sync tests

---

simulator.go

This PR fixes an error which caused a nil deref if the simulator image fails to build, as was the case in https://github.com/hyperledger/besu/issues/797

simulator: fix nil deref on failure to build simulators

---

clients/besu/besu.sh

hyperledger/besu#797 brought up a fast sync issue that is a result of the test chain not conforming to certain configured minimums.
These flags are there to protect against chain reorgs and bad pivot-block-selection while fast syncing. I'm curious why geth's sync doesn't need these precautions! If you have a link to a resource that explains how geth's sync gets around these that would be lovely.

add besu fast-sync config flags for contrived test chains

---

clients/besu/besu.sh

Change the besu block import step to do a bulk import instead of one
file at a time.  This will allow some tests to finish that otherwise
would time out.
Requres besu 1.4.7-SNAPSHOT or newer.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>

Besu bulk block import

---

clients/besu/besu.sh
clients/openethereum/Dockerfile
simulators/ethereum/graphql/graphql.go
test.sh

fixes #310 and #311
Geth now serves graphql on the same port as json-rpc http requests. This PR changes the graphql for besu to also use `8545`.

Fix clientproblems

---

clients/besu/besu.sh
clients/go-ethereum/geth.sh
simulators/ethereum/graphql/graphql.go

This might make all geth-graqhql tests fail, but should allow the consensus tests to work again

fixes #314, use separate port for graphql 

---

chaintools/chaintools.go

This PR fixes an ineffectual error assignment that prevented a genesis file from being accepted with the command `chainGenesis`. 
The following error would result: 
```
CRIT[09-08|14:35:38] failed to read genesis json              error=nil
```
Now, if a user specifies the `chainGenesis` command after the `chainGenerate` command, a more descriptive error will be logged:
```
CRIT[09-08|14:37:33] failed to read genesis json              error="open : no such file or directory"
```
This does not solve the problem, however, that the order in which a user specifies `chainGenerate` and `chainGenesis` matters for whether the given filepath+name is actually recognized.
The valid order is: 
```
-chainGenesis <filepath> -chainGenerate <bool>
```

chaintools: ineffectual error assignment preventing genesis file from being opened

---

README.md
hive.go
simulators/common/providers/local/local_test.go

This PR fixes a build error that occurs from the default value of the `--client` flag pointing to a branch that does not exist.

change default branch for geth dockerhub image from master to latest

---

README.md
clients/aleth/Dockerfile

This PR fixes a broken link, the aleth Dockerfile (tag was incorrectly defined as master instead of latest), and some incorrect documentation for trinity in the README.md

additional fixes for docs and aleth Dockerfile with wrong tag

---

README.md
simulators/common/providers/local/local_test.go

This PR fixes some inaccurate documentation for the default branch of the docker image for the parity client. It should be `latest`, not `master`.

change default branch for parity dockerhub image from master to latest

---

clients/trinity/Dockerfile
clients/trinity/enode.sh
clients/trinity/mapper.jq
clients/trinity/trinity.sh

With these changes, the client builds and actually starts. It now
supports most of the options that other clients support as well. The
initial chain import is still broken unfortunately, so it can't run the
consensus tests yet.

clients/trinity: fix trinity docker build and startup script

---

clients/trinity/Dockerfile

I broke the build when removing the genesis.json and config.json files.
This fixes it by removing the corresponding ADD statements in the Dockerfile.

clients/trinity: fix docker build one more time

---

hive.go
hiveErrorReporting.go
images.go
shell.go
simulator.go

This PR adds error handling in the cases that: 
**client:**
- can't find user-specified docker image in `clients` dir (in which case, continue test with the clients that have been successfully built, but log critical error)
- no clients get spun up at all (in which case, kill the test)
**simulation:** 
- simulation is not found (in which case, kill the test)
- simulation image build failed (in which case, kill the test)
The errors will be logged both to stderr and to a file `containerErrorReport.json`

hive: add error handling for if dockerfile/image can't build or is not found

---

clients/nethermind/Dockerfile
clients/nethermind/genesis.json
clients/nethermind/nethermind.sh

This changes the default branch to 'alpine' because the Nethermind team
is not pushing to the 'latest' tag anymore. The tag actually points to
an Ubuntu-based image though.
It also adds back the version.json and genesis.json files because they
are required for all tests.

clients/nethermind: fix some more issues

---

images.go

This allows running hive with client names that do not contain the
branch explicitly (e.g. "go-ethereum" instead of "go-ethereum_latest").
If there is no branch name, the default from the Dockerfile is used.
This also removes the substring-based matching of client names and
requires an exact match instead. It was previously possible to run hive
with weird patterns such as `--client e_latest`, matching all client names
containing 'e'. The client names now need to be spelled out in full, which
is more predictable.

hive: improve client name matching

---

clients/aleth/Dockerfile
clients/besu/Dockerfile
clients/nethermind/mapper.jq
clients/openethereum/Dockerfile
clients/trinity/Dockerfile
clients/trinity/genesis.json
clients/trinity/mapper.jq
clients/trinity/trinity.sh

This fixes a few more issues with the client scripts:
- Aleth: use the 'nightly' tag by default
- OpenEthereum: add version.json to make it launch again
- Nethermind: fix some issues in mapper.jq
- Trinity: various tweaks to mapper.jq to make it work correctly
- Besu: allow pulling docker tags other than 'develop'

clients: fix more client issues

---

clients/go-ethereum/geth.sh
simulators/ethereum/consensus/main.go

Fixes https://github.com/ethereum/hive/issues/357 , adds framework support for yolov2 / berlin.

simulators/consensus: add yolov2/berlin support

---

cmd/hiveview/assets/app.js
cmd/hiveview/assets/assets.go
cmd/hiveview/listing.go

This removes the `description` key from the listing file because it's not used
by the viewer. Also changes the default sort order of the tests table to show the
failed tests first.

cmd/hiveview: remove description in listing

---

internal/libhive/docker.go

Doesn't really make sense to use scaling here, checking every 100ms
doesn't hurt and makes tests run faster.

internal/libhive: remove scaling of client startup check timeout

---

containers.go
go.mod
go.sum
hive.go
images.go
internal/libhive/docker.go
internal/libhive/testmanager.go
simulator.go

These were already available as globals, but not passed to libhive.
This also removes some other unused code in the main hive executable.

internal/libhive: use client version info and start timeout

---

clients/aleth/Dockerfile
clients/aleth/genesis.json

All other clients have it, and it's required for running simulations
which don't care about the genesis block.

clients/aleth: add default genesis.json

---

simulators/ethereum/graphql/Dockerfile
simulators/ethereum/graphql/go.mod
simulators/ethereum/graphql/go.sum

The simulation module had to be renamed temporarily in order to make it
build. Now that the parent hive module no longer includes the packages
of this simulation module, we can put the correct name back.

simulators/ethereum/graphql: rename module back to proper name

---

simulators/ethereum/consensus/Dockerfile
simulators/ethereum/consensus/go.mod
simulators/ethereum/consensus/go.sum

The simulation module had to be renamed temporarily in order to make it
build. Now that the parent hive module no longer includes the packages
of this simulation module, we can put the correct name back.

simulators/ethereum/consensus: rename module back to proper name

---

simulators/devp2p/discv4/discv4.go
simulators/devp2p/discv4/go.mod
simulators/devp2p/discv4/go.sum

This updates the discovery simulation to work with the new 'by-name'
docker networks API. It also fixes running the simulation with multiple
client types. This previously failed because it tried to create the
network more than once.

simulators/devp2p/discv4: update to new docker networks API

---

internal/libhive/docker.go

This PR is an alternative to #398 . Instead of adding additional information to the test manager, when RemoveNetwork is called, we should just disconnect all containers from the network first to ensure a clean removal.

internal/libhive: disconnect containers from network when removing network

---

clients/besu/besu.sh

This lowers the startup time from 9s to 5s by combining the block import
and client startup commands into a single invocation.

clients/besu: use the --run block import option to speed up startup

---

simulators/ethereum/graphql/graphql.go

It would be nice to also print the response body upon http status mismatch to provide further context to errors. At the moment, if there is a header mismatch, it only prints out the header mismatch (expected vs. got), but no response body to see what went wrong.

simulators/ethereum/graphql: print response body when status code mismatch to provide more err context

---

simulators/ethereum/graphql/testcases/03_eth_call_BlockLatest.json

This PR changes the `03_eth_call_BlockLatest` graphql test case `from` field to a hex string to match the `to` field.
If there is a valid reason for the difference in input formats, I will close this PR.

simulators/ethereum/graphql: change `from` to hex string to match `to` in eth_call_BlockLatest

---

cmd/hivechain/generate.go

This PR adds a check to make sure the blockchain config is not nil. A nil blockchain config causes geth to hang when inserting chain [here](https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_signing.go#L45).

cmd/hivechain: error out on nil blockchain config

---

simulators/ethereum/graphql/testcases/42_graphql_blocks_byRange.json

Geth deprecated the ability to take a hex string as a parameter for a query on `Block` with [this PR](https://github.com/ethereum/go-ethereum/pull/21883).

simulators/ethereum/graphql: replace #42 test query with decimal instead of hex string

---

cmd/hiveview/assets/app.js
hivesim/testapi_test.go
internal/libhive/api.go
internal/libhive/data.go
internal/libhive/testmanager.go

This PR changes client version reporting to only report the client versions at the suite level to not cloud the log output.
It also removes test case ID reporting as it's not really necessary.

internal/libhive: report client versions in suite

---

clients/go-ethereum/mapper.jq

This should unbreak the Berlin consensus tests with geth.

clients/go-ethereum: set yolov3Block in chain config

---

internal/libdocker/container.go
internal/libhive/api.go
internal/libhive/testmanager.go

This restructures things a bit so that `DeleteContainer` will be called exactly once for every client container. This avoids error messages in libdocker saying that deleting the container failed.

internal/libhive: fix double delete of failed client container

---

simulators/ethereum/graphql/testcases/02_eth_call_Block8.json
simulators/ethereum/graphql/testcases/16_eth_getBlock_byNumber.json
simulators/ethereum/graphql/testcases/17_eth_getBlock_byNumberInvalid.json
simulators/ethereum/graphql/testcases/20_eth_getBlockTransactionCount_byNumber.json
simulators/ethereum/graphql/testcases/23_eth_getLogs_matchTopic.json
simulators/ethereum/graphql/testcases/28_eth_getTransaction_byBlockNumberAndIndex.json
simulators/ethereum/graphql/testcases/29_eth_getTransaction_byBlockNumberAndInvalidIndex.json

This PR changes the following test cases to use number instead of hexadecimal as the input parameter for block number: 
* `02_eth_call_Block8 `
* `16_eth_getBlock_byNumber`
* `20_eth_getBlockTransactionCount_byNumber`
* `23_eth_getLogs_matchTopic`
* `28_eth_getTransaction_byBlockNumberAndIndex`
* `29_eth_getTransaction_byBlockNumberAndInvalidIndex`
With [this PR](https://github.com/ethereum/go-ethereum/pull/21883), geth no longer accepts strings for the block number parameter. Besu accepts both. 
Additionally, I added an additional valid response for `17_eth_getBlock_byNumberInvalid`, but it is still failing as there is a discrepancy in error reporting between Besu and Geth (discussed [here](https://github.com/ethereum/hive/pull/426#issuecomment-775074987)) that will hopefully be solved …

simulators/ethereum/graphql/testcases: change block number input to number instead of hexadecimal

---

simulators/ethereum/graphql/testcases/30_eth_getTransaction_byHash.json
simulators/ethereum/graphql/testcases/35_graphql_pending.json

This PR adds an additional valid response for the `30_eth_getTransaction_byHash` test case and also adds the 0x prefix to the `from` parameter in the `35_graphql_pending` testcase. 
There is still an issue with `35_graphql_pending` where geth returns an empty array of transactions:  
```
HTTP response code: 200 OK
expected value(s):
{
"data": {
"pending": {
"account": {
"balance": "0x140"
},
"call": {
"data": "0x0000000000000000000000000000000000000000000000000000000000000001",
"status": 1
},
"estimateGas": 21000,
"transactionCount": 1,
"transactions": [
{
"gas": 1048575,
"nonce": 50
}
]
}
}
} 
_____________________
got: {
"data": {
"pending": {
"account": {
"balance": "0x140"
},
"call": {
"data": "0x0000000000000000000000000000000000000000000000000000000000000001",
"status": 1
}, …
```

simulators/ethereum/graphql/testcases: fix testcases

---

simulators/devp2p/eth/eth.go

The lastest besu logfile from the eth protoocol is `59Mb`. Let's decrease that a bit

simulators: decrease eth simulator loglevel a bit

---

docs/clients.md
docs/simulators.md
go.mod
hive.go
hivesim/hive.go
hivesim/hive_test.go
hivesim/testapi.go
internal/libdocker/builder.go
internal/libhive/api.go
internal/libhive/dockerface.go
internal/libhive/testmanager.go

Changes:
- Load clients into single collection of definitions, don't separate versions, images, metadata into different maps.
- List the definitions in the API clients listing, except docker image: metadata such as the role is important for test-suites, docker-strings not so much.
- Update client loading, no changes required to clients. Default metadata is an "eth1" role. 
Eth1 simulators should update like:
```diff
suite.Add(hivesim.ClientTestSpec{
+               Role: "eth1',
Run: runDiscoveryTest,
Parameters: hivesim.Params{
"HIVE_LOGLEVEL": "5",
},
})
```
To ensure the test only ever runs against the intended kind of client. If the test runner does not provide eth2 client names by accident, the old behavior still works.
Next, we can make other tests that consume "beacon", …

internal/libhive: client definitions, metadata file loading, client-roles

---

hivesim/data.go
hivesim/hive.go
hivesim/hive_test.go
hivesim/options.go
hivesim/testapi.go
internal/libdocker/container.go

TLDR: introduce Option pattern to client-start, to allow dynamic file sources, and easily extend/compose many options.
Changes:
- `Params` is a `StartOption`
- File options:
- Static files can be added (defined as a `dst path -> src path` dict like before)
- New: Dynamic files can be added (defined as a `dst path -> open function` dict)
- `StartOptionFn` to define minimal start options (the `setup` struct is usage is limited to the hivesim package). (should we hide this function type from public API?)
- `Bundle` options together to make test preparation easy. A 1000 keystore files to worry about? Bundle them. A repeated test with configuration files and parameters? Bundle them.
- Replaces Tar file support to do multiple files like in previous draft.
- Parameters can override parameters, …

hivesim: StartOption for client configuration

---

docs/simulators.md
hivesim/data.go
hivesim/hive.go
hivesim/hive_test.go
hivesim/testapi.go
internal/fakes/backend.go
internal/libdocker/container.go
internal/libhive/api.go
internal/libhive/data.go
internal/libhive/dockerface.go

Changes:
- ClientRunProgram in hivesim can run a command in a container
- Hive API endpoint to run program in node
- Test backend implements basic mock + hook
- Test to see API work
This is a first attempt to generalize the "enode.sh" functionality (idea from earlier discussion with @fjl).
It misses the scope limit to `/hive-bin/<program>` still, I didn't find a clean way to limit the command (especially if it's shell code).
TODO The API is tested, but the docker backend implementation is not.
This helps:
- Run more advanced eth2 tests, e.g. stop validator, export keystores and slashing DB out of a container, then start again. (and import it into another validator). E.g. `/hive-bin/export-keys.sh`
- Connect eth2 clients. Eth2 nodes don't have an enode-url formatted address, and the beacon …

internal/libhive, hivesim: add client script exec API

---

simulators/ethereum/consensus/genesis_test.go
simulators/ethereum/consensus/main.go
simulators/ethereum/consensus/types.go

Currently, nethermind is failing a lot of tests due to genesis mismatch, specifically because of `baseFeePerGas` not being set correctly. This results in output json of `124Mb`, because the expected json and the client response are printed out for each failing test (40K+). 
This PR reduces the output to only print the actual differences. 
```
genesis hash mismatch:
want 0xafa8fc2deb658d8120f4011e459159a6472b88e2dfed6518640be01dbbfd20a9
got 0xa29ba2a76546b56f331f02e70b24c4a1452b1b392e1d2fe51828ff57f551d62e
genesis.baseFeePerGas - have 1000000000, want 11 
```

simulators/consensus: reduce output on genesis mismatches

---

internal/libdocker/docker.go

This PR fixes a small typo I encountered while working with the testing rig: `interfaes` -> `interfaces`.

internal/libdocker: fix typo `interfaes` -> `interfaces`

---

clients/nethermind/mapper.jq
clients/openethereum/mapper.jq

Nethermind and Openethereum are failing some hive consensus tests (Constantinople and transition ones), because values of `eip1283Transition` and `eip1283DisableTransition` are always `"0x0"`. This PR is fixing this issue.

clients/nethermind, clients/openethereum: fix eip1283 activation block

---

clients/aleth/Dockerfile
clients/besu/Dockerfile
clients/go-ethereum/Dockerfile
clients/nethermind/Dockerfile
clients/openethereum/Dockerfile
clients/trinity/Dockerfile
hivesim/hive.go
hivesim/hive_test.go
hivesim/testapi.go

Add API HTTP endpoint to fetch the eth client's enode/IP on a custom docker network.
This addition will be useful to create test cases where a secondary network is used as the main connection between clients, and can be disconnected on demand to simulate network partitioning.

hivesim: add get client enode in specific network / clients: add symlink to enode.sh in hive-bin

---

hivesim/hive.go
hivesim/hive_test.go
hivesim/options.go
internal/libhive/api.go
internal/libhive/testmanager.go

Adds an option to the StartClient API to include a set of networks in the request to which the new client must already be connected at startup.
The added "NETWORKS" form value must be an array of strings containing the names of existing networks to which the new client will be connected before it starts to run.
Example application of this new feature includes Consensus client Lighthouse where enr-address is passed as command line parameter for the client to generate a valid ENR in a different network than the default.

internal/libhive: add client option for initially connected networks

---

clients/erigon/Dockerfile
clients/erigon/erigon.sh
clients/erigon/mapper.jq
simulators/ethereum/engine/go.mod
simulators/ethereum/engine/go.sum

This PR adds changes required to Erigon client to support the Engine API.
The rpcdaemon is also removed since this is now part of the main Erigon binary when the --http flag is added.

clients/erigon: engine/merge erigon changes

---

clients/lighthouse-bn/Dockerfile
clients/lighthouse-bn/lighthouse_bn.sh
clients/merge-go-ethereum/Dockerfile
simulators/eth2/testnet/helper.go
simulators/eth2/testnet/nodes.go
simulators/eth2/testnet/prepared_testnet.go
simulators/eth2/testnet/scenarios.go
simulators/eth2/testnet/setup/eth1config.go

This retains the ability to spawn a testnet using `ethash` for the pre-transitioned portion of the testnet, but in the configurations I've switched to using `clique` instead.

Switch to using clique for merge transition simulator

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/helper.go

This PR fixes Engine API tests that perform a re-org, in order to ensure that the forkchoiceUpdated directive always points to a side-chain and does not attempt to jump back and forth to previous blocks on the canonical chain.
However, a simple sanity test is added which performs this behavior, but in this case the test simply expects that the client does not fail and is capable of progressing after such event.

simulators/engine: Fix re-org tests

---

clients/erigon/erigon.sh
clients/merge-go-ethereum/geth.sh
clients/merge-nethermind/Dockerfile
clients/merge-nethermind/mkconfig.jq
clients/merge-nethermind/nethermind.sh
simulators/ethereum/engine/README.md
simulators/ethereum/engine/authtests.go
simulators/ethereum/engine/engineclient.go
simulators/ethereum/engine/main.go

This PR adds the following JWT authentication tests:
- No time drift, correct secret
- No time drift, incorrect secret (shorter)
- No time drift, incorrect secret (longer)
- Negative time drift, exceeding limit, correct secret
- Negative time drift, within limit, correct secret
- Positive time drift, exceeding limit, correct secret
- Positive time drift, within limit, correct secret

simulators/engine: Add JWT Authentication tests

---

clients/erigon/Dockerfile
clients/ethereumjs/Dockerfile
clients/go-ethereum/Dockerfile
clients/go-ethereum/geth.sh
simulators/eth2/testnet/nodes.go

This PR fixes the value of the Engine API Port across all the Simulators/Clients, making the following changes:
- Simulators
- eth2/testnet: 8550 -> 8551
- ethereum/engine: 8551 (No change)
- Clients
- go-ethereum: 8550 -> 8551
- nethermind: 8551 (No change)
- ethereumjs: Expose port 8551
- erigon: Expose port 8551

Match Engine API Port Across Simulators/Clients

---

simulators/ethereum/engine/clmock.go
simulators/ethereum/engine/engineclient.go
simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/helper.go
simulators/ethereum/engine/testenv.go
simulators/ethereum/engine/teststruct.go

This PR includes a refactoring of the Test Verification syntax to make the test cases much more readable and explicit on what they expect as outcome.
The `Expect*` methods are introduced to allow test cases to explicitly indicate what to expect from each call they perform, to either the Engine API or the Eth JSON-RPC.
E.g. this verification:
```
fcResp, err := t.Engine.EngineForkchoiceUpdatedV1(t.Engine.Ctx(), &forkchoiceState, nil)
if err != nil {
t.Fatalf("FAIL (%s): ForkchoiceUpdated under PoW rule returned error (Expected INVALID_TERMINAL_BLOCK): %v, %v", t.TestName, err)
}
if fcResp.PayloadStatus.Status != "INVALID_TERMINAL_BLOCK" {
t.Fatalf("INFO (%v): Incorrect EngineForkchoiceUpdatedV1 response for invalid PoW parent (Expected PayloadStatus.Status=INVALID_TERMINAL_BLOCK): %v", …
```

simulators/ethereum/engine: Refactor Test Verification Syntax

---

clients/merge-nethermind/Dockerfile
clients/merge-nethermind/mapper.jq

This PR updates the merge-nethermind branch to kiln_shadowfork.
Also, HIVE_MAX_EXTRA_DATA_SIZE was implemented to allow nethermind to sync pre-merge blocks that were generated using clique, which have an extradata size higher than the default of 32.

clients/merge-nethermind: update docker branch, increase extradata for clique

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/enginetests.go

Adds first batch of new tests based on the coverage document by @mkalinin ([link](https://hackmd.io/vjgC9hV_TrK1ZuftVm1rZA)).
Tests added:
- EL Not SYNCING: Invalid hash payload extending side chain
- EL SYNCING: Invalid hash payload extending canonical chain
- EL SYNCING: Invalid hash payload extending side chain chain
Follow up PRs will fill remaining gaps. Please advice if this format is fine: small number of new tests per PR, or a big PR with all test cases is better.

simulators/ethereum/engine: Increase bad hash tests coverage

---

simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/testenv.go

Currently most of the tests abort if `eth_sendRawTransaction` returns an error.
In the case of Erigon, the client returns `pool not started yet` when the it has just started.
This PR is a simple change to retry until the method succeeds or the test timeout, whichever happens first.

simulators/ethereum/engine: Retry Sending Transactions

---

simulators/ethereum/engine/enginetests.go

The "Out of Order Payload Execution (go-ethereum)" test fails with this panic. I think it is because of this line https://github.com/ethereum/hive/blob/82fd6c45cc8b459c58344efbfa464c22ea963421/simulators/ethereum/engine/enginetests.go#L1190 which probably accesses the engine client array out of bounds. We overwrote the i value in the inner loop
```
panic: runtime error: index out of range [10] with length 1
goroutine 536 [running]:
github.com/ethereum/hive/hivesim.runTest.func2.1()
/go/pkg/mod/github.com/ethereum/hive@v0.0.0-20220216101708-2784ea3e7eea/hivesim/testapi.go:327 +0x7b
panic({0x839740, 0xc0000260c0})
/usr/local/go/src/runtime/panic.go:838 +0x207
main.outOfOrderPayloads(0xc000220630)
/source/enginetests.go:1190 +0x9aa
main.RunTest({0x86da77, 0x1e}, 0xb?, 0xc0001a8f70?, …
```

simulators/ethereum/engine: fix loop variable override

---

simulators/ethereum/engine/enginetests.go

As discussed on discord:
```
Geth fails one hive test that we should discuss imo @Mikhail Kalinin [mkalinin] @Mario Vega  maybe @MarekM 
Invalid ParentHash NewPayload: This test inverts a byte in the payloads parentHash which means we can not recognize it as the parentHash anymore. Geth will now on receiving this payload start a sync since we don't have the payload and nothing really speaks against us syncing it (it might be a valid payload with a valid parent). 
The test expects ACCEPTED or INVALID but we return, since we started the sync, SYNCING
Nethermind passes the test, while Erigon also returns SYNCING.
Imo the correct fix would be to modify the test to also accept SYNCING as a return value, since the EL might start a sync
```
```
You're right and SYNCING is totally fine in this …
```

simulators/ethereum/engine: allow for SYNCING in invalid payload tests

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/helper.go
simulators/ethereum/engine/testenv.go

This PR implements test case where the CL attempts to re-org into a side chain with unknown payloads to the EL.
The test first generates a side chain with N payloads, which at some point contains an invalid payload, but the side chain remains unknown to the EL:
```
CommonAncestor◄─▲── P1 ◄── P2  ◄─ P3  ◄─ ... ◄─ Pn
│
└── P1' ◄─ P2' ◄─ P3' ◄─ ... ◄─ Pn'
```
After Pn, the CL performs an `fcU(Pn')` to the head of the side chain.
Then the CL proceeds to reveal the remaining payloads in the following order:
```
newPayload(Pn')
...
newPayload(P2')
newPayload(P1')
```
Currently two scenarios are implemented:
- `P1'` is invalid, and since `CommonAncestor` is known to the EL, the response to `newPayload(P1')` should be `INVALID` with `latestValidHash==CommonAncestor.Hash`.
- `P3'` is invalid and …

simulators/ethereum/engine: Re-org to Chain with Missing Invalid Payload

---

simulators/ethereum/engine/clmock.go

This PR is a small change to add a verification within the CL Mock to always check the response from the `engine_forkchoiceUpdatedV1` assuming a "happy path" the module always tries to follow.
Following checks are added:
```
{
payloadStatus: {
status: VALID,
latestValidHash: forkchoiceState.headBlockHash,
validationError: null
},
payloadId: null
}
```
**Update:** Added checks to verify that the payload built is coherent with the payload attributes requested, and also that the final produced block does comply with the EIP-3675 requirements (empty uncle hash, zero nonce, mixHash == prevRandao, difficulty == 0).
Checklist: https://hackmd.io/RxjgShIvSa--rnc4hhKAnQ?view

simulators/ethereum/engine: Verify full ForkchoiceUpdated response on CLMock

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/enginetests.go

Adds the following test suggested by @mkalinin in his [checklist](https://hackmd.io/RxjgShIvSa--rnc4hhKAnQ?view):
Inconsistent ForkchoiceState:
A: Genesis <- P1 <- P2 <- P3, B: Genesis <- P1' <- P2' <- P3'
EL client starts with fully imported A and B
forkchoiceUpdated(finalized: A.P1, safe: A.P2, head: A.P3)
EL successfully re-orgs to A.P3, finalized and safe blocks are as expected
forkchoiceUpdated(finalized: A.P1, safe: A.P2, head: B.P3')
forkchoiceUpdated(finalized: A.P1, safe: B.P2', head: A.P3)
forkchoiceUpdated(finalized: B.P1', safe: A.P2, head: A.P3)
{error: {code: -38002, message: "Invalid forkchoice state"}} in all cases listed above
forkchoiceUpdated(finalized: B.P1', safe: B.P2', head: B.P3')
EL successfully re-orgs to B.P3, finalized and safe blocks are as expected
Current …

simulators/ethereum/engine: Add Inconsistent ForkchoiceState Tests

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/mergetests.go

Adds the following test cases:
- Two Block Post-PoS Re-org to Higher-Total-Difficulty PoW Chain
- Two Block Post-PoS Re-org to Lower-Total-Difficulty PoW Chain
- Two Block Post-PoS Re-org to Higher-Height PoW Chain
- Two Block Post-PoS Re-org to Lower-Height PoW Chain
- Transition on an Chain with Invalid Terminal Block, Incorrectly Configured Higher Total Difficulty
- Transition on an Chain with Invalid Terminal Block, Incorrectly Configured Lower Total Difficulty
The first four test cases attempt to re-org a client to a valid side-chain after a couple of PoS blocks were already produced on the canonical chain, where the side chain and the canonical chain have different Total Difficulty and/or different heights.
The last two test cases attempt to re-org onto an invalid PoW chain with an …

simulators/ethereum/engine: Add PoW Merge Transition Test Cases for Coverage Increase

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/enginetests.go

Adds test case to increase coverage, described [here](https://github.com/txrx-research/TestingTheMerge/blob/main/tests/engine-api.md) as `Re-org back to canonical chain while SYNCING`.
Test scenario might have already been implicitly covered by other tests.

simulators/ethereum/engine: Add Test Case to Re-org Back to Canonical Chain While SYNCING

---

simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/testenv.go
simulators/ethereum/engine/teststruct.go

This PR adds a few extra coverage checks on the following tests:
- Invalid GetPayload/NewPayload/ForkchoiceUpdated: Verify that the PoW chain continues if the Terminal Block is incorrect.
- Latest Block Status After NewPayload/HeadBlockHash/SafeBlockHash/FinalizedBlockHash: Verify the same behavior applies on the transition block.
- Check transaction receipt after NewPayload/HeadBlockHash/SafeBlockHash/FinalizedBlockHash: Transaction Receipt should not be available until the HeadBlockHash is updated via ForkchoiceUpdated

simulators/ethereum/engine: Add Transition Block Checks

---

simulators/ethereum/engine/engineclient.go
simulators/ethereum/engine/enginetests.go

This PR removes `INVALID_TERMINAL_BLOCK` and replaces it with `{status: INVALID, latestValidHash=0x00..00}`, in all appropriate tests, according to changes in https://github.com/ethereum/execution-apis/pull/217.

simulators/ethereum/engine: Remove INVALID_TERMINAL_BLOCK

---

simulators/ethereum/engine/clmock.go
simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/mergetests.go
simulators/ethereum/engine/testenv.go

This changes allows the CL Mock to simulate the proper behavior of a Consensus Layer client, where the blocks are not immediately finalized (no single-slot-finality yet).
On the transition to PoS, the ForkchoiceUpdated calls from the CL Mock will, by default, now look like this:
```
NewPayload(P1)
ForkchoiceUpdated(head: P1, safe: 0, finalized: 0)
NewPayload(P2)
ForkchoiceUpdated(head: P2, safe: P1, finalized: 0)
NewPayload(P3)
ForkchoiceUpdated(head: P3, safe: P2, finalized: P1)
```
This delay is customizable if we need to extend the finalization period to more slots.
Discord thread link: https://discord.com/channels/595666850260713488/974664364466511972

simulators/ethereum/engine: CLMock safe/finalized Slot Delay

---

clients/besu/besu.sh

Signed-off-by: Daniel Lehrner <daniel.lehrner@consensys.net>
This PR configures Besu to use the hardcoded JWT secret. It's needed to pass all of the JWT tests of the engine simulator

clients/besu: add JWT secret

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/enginetests.go

Implements test case "Re-org to chain with invalid transition block" suggested in https://github.com/txrx-research/TestingTheMerge/pull/4/files#diff-f9223f9dc89130dc64351addac949a8248ec031bcde0561497a06bffd7f74d2cR376
Currently clients Geth, Nethermind and Besu are failing this test because `newPayload(INV_P1)` returns `latestValidHash==TERMINAL_BLOCK`, and the test expects `latestValidHash==0x00..00`.
Erigon is failing when importing PoW chain as in other existing test cases.
cc @mkalinin @MariusVanDerWijden @MarekM25 @garyschulte

simulators/ethereum/engine: Re-org to Chain with Invalid Transition

---

simulators/ethereum/engine/enginetests.go

Allow invalid status in case EL is able to determine it is invalid.

simulators/ethereum/engine: allow invalid status after invalid block

---

simulators/ethereum/engine/enginetests.go

On the "ForkchoiceUpdated Invalid Payload Attributes" tests, the forkchoice was set to instant finality and then rolled back on the subsequent ForkchoiceUpdated call, which produced unintended behavior on some clients, which is something the test did not intend to verify.
Fix is to send the same hash of the latest forkchoice for `SafeBlockHead` and `FinalizedBlockHead`.

simulators/ethereum/engine: Fix Finality On Invalid Payload Attributes Test

---

clients/nimbus-bn/Dockerfile
clients/nimbus-bn/hive.yaml
clients/nimbus-bn/nimbus_bn.sh
clients/nimbus-vc/Dockerfile
clients/nimbus-vc/hive.yaml
clients/nimbus-vc/nimbus_vc.sh

Adds `nimbus-bn` and `nimbus-vc`, which are compiled from source from branch https://github.com/status-im/nimbus-eth2/tree/kiln-dev-auth, with a custom setting `SECONDS_PER_SLOT=3`, to allow quicker test runtimes.

clients/nimbus: add nimbus beacon node and validator client

---

simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/teststruct.go

- Add test that make sure obtained transaction's blockhash is the main chain blockhash.
- Not sure if you want this since this is nethermind specific issue.
- But here you go.

simulators/ethereum/engine: check transaction blockhash after re-orgs

---

clients/besu/besu.sh

Signed-off-by: Daniel Lehrner <daniel.lehrner@consensys.net>
The `rpc` test suite for Besu is failing a lot of tests, because the client start with fast sync instead of full sync and gets stuck. This PR fixes the configuration of the sync mode for all existing test suites.
We cannot only rely on `HIVE_NODETYPE` for it, but need to take `HIVE_TERMINAL_TOTAL_DIFFICULTY` into consideration as well, because the `engine` test suite needs full sync (at least for Besu), but `HIVE_NODETYPE` is empty.

clients/besu: update sync mode

---

clients/go-ethereum/geth.sh

We changed something in geth that makes a lot of tests fail in snap sync mode.
Basically you can not import blocks one by one in snap sync mode, the snap sync has to finish before importing blocks one by one, otherwise we might overwrite data that is already in the database. 
The tests depend on this one-by-one importing though, which is only available to a full synced node in geth. This changes the default sync mode to full.

clients/go-ethereum: set syncmode=full by default

---

clients/nimbus-bn/nimbus_bn.sh

Fix the ENR `--bootstrap-node` command line option to split from comma-separated value.

clients/nimbus-bn: Fix bootstrap nodes option

---

clients/besu/enode.sh

Implement a simple retry strategy when getting the enode URL from Besu, since it could not be yet ready to serve that information on the first call.
fixes #593

clients/besu: implement retry mechanism to get enode

---

simulators/ethereum/rpc-compat/main.go

The tests now use chain ID `1337` so the hive simulator needs to be updated.

simulators/ethereum/rpc-compat: update chain id to match tests

---

hiveproxy/Dockerfile
hiveproxy/proxy.go
hiveproxy/proxy_test.go
internal/libdocker/proxy.go

This fixes a panic in internal/libdocker, which could occur
when hive was interrupted while setting up the proxy.

hiveproxy: handle errors during connection setup

---

hiveproxy/proxy.go
hiveproxy/proxy_test.go
hiveproxy/tool/main.go
internal/libdocker/container.go
internal/libdocker/proxy.go

These changes should make the proxy work a bit better.
In my testing, I found that hive would sometimes hang while setting up
the proxy container, and killing the process would leave the container behind.
With these changes, the proxy container will eventually exit by itself when hive
loses track of it for some reason. Also, the setup is somehow more reliable
with the direction of the RPC stream switched: now the frontend waits for the
backend to connect before continuing.

hiveproxy, internal/libdocker: proxy setup improvements

---

hive.go
hivesim/hive_test.go
internal/fakes/builder.go
internal/fakes/container.go
internal/libdocker/builder.go
internal/libdocker/proxy.go
internal/libhive/api.go
internal/libhive/dockerface.go
internal/libhive/inventory_test.go
internal/libhive/run.go
internal/libhive/run_test.go
internal/libhive/testmanager.go

This moves all logic related to a simulation run into the library. The
runner has also gained a couple of new features in this change:
Pass/fail stats are now collected across simulators, enabling the hive
tool to exit with a non-zero status when tests have failed.
Another new feature of the library: the client list can now be overridden
separately for every individual simulator run. This will come in handy when
we create a tool to run multiple simulations from a config file.

hive: move simulation runner to internal/libhive

---

simulators/ethereum/engine/clmock.go
simulators/ethereum/engine/engineclient.go
simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/mergetests.go
simulators/ethereum/engine/node.go
simulators/ethereum/engine/testenv.go

Fixes:
- During hive runs it was detected that some of the transactions from previous tests were being replayed on tests, and it was because the secondary node was not being correctly terminated.
- Checking the TTD no longer panics on error, and therefore subsequent tests are no longer aborted
- ~~HIVE_CHECK_LIVE_PORT is now set to the Engine API port 8551 (#603 )~~ Requires to check multiple live ports to properly fix
- Minor log improvements
Temporarily disabled test cases:
- Invalid Ancestor Chain Re-Org, Invalid Number, Invalid P9', Reveal using sync
- Invalid Ancestor Chain Re-Org, Invalid PrevRandao, Invalid P9', Reveal using sync

simulators/ethereum/engine: CL Mock Test Fixes

---

clients/teku-bn/teku_bn.sh

Adds client support for `HIVE_ETH2_SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` setting:
- `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` is set in `config.yaml`
- `--Xnetwork-safe-slots-to-import-optimistically` is set as parameter to the same value

clients/teku-bn: Add SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY

---

clients/prysm-bn/Dockerfile
clients/prysm-bn/hive.yaml
clients/prysm-bn/minimal.Dockerfile
clients/prysm-bn/prysm_bn.sh
clients/prysm-vc/Dockerfile
clients/prysm-vc/hive.yaml
clients/prysm-vc/prysm_vc.sh

Adds Prysm beacon node and validator client images.
A few considerations:
- Simulator requires that Altair and Bellatrix fork on different epochs (e.g. Altair on epoch 1, and bellatrix on epoch 2) which results in long test case runtimes.
- Requires changes to all FORK_VERSION configurations because Prysm does not admit testnet identifiers to have the same versions as mainnet.
- Prysm's REST API endpoint `/eth/v2/debug/beacon/states/` returns error 404. This endpoint is used by method `getHealth` and therefore it fails, which might require a workaround.
These considerations aside, the client is functional and most of the test cases in https://github.com/ethereum/hive/pull/569 are passing.

clients/prysm: add Prysm Beacon Node and Validator Client 

---

simulators/ethereum/engine/authtests.go
simulators/ethereum/engine/main.go

In order to mitigate false negatives, introduce retry count for some authentication tests that depend on time drift.
Reasoning is that the test is not attempting to verify how precise the client is, but to verify correct configuration.
Fixes #602.
Break test cases into separate suites: engine, transition, auth.
Suites can run with commands `--sim.limit "engine/"`, `--sim.limit "transition/"`, or `--sim.limit "auth/"`.

simulators/ethereum/engine: Fix time drift auth tests, break tests into separate suites

---

clients/nethermind/nethermind.sh

- Nethermind script now reads `HIVE_LOGLEVEL` and adds the appropriate parameter

clients/nethermind: Add `--sim.loglevel` Support for Nethermind

---

clients/go-ethereum/geth.sh
clients/nethermind/mkconfig.jq
clients/nethermind/nethermind.sh
simulators/ethereum/engine/clmock.go
simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/helper.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/sync.go
simulators/ethereum/engine/synctests.go

Enhances Post-Merge sync tests by providing several variations of each sync tests where the variation is client dependent.
- Sync tests for geth are now performed on `archive`, `full` and `snap` modes.
- Sync tests for nethermind are now performed on `archive`, `fast` with varying pivot blocks.
- New test case `Incremental Post Merge Sync` passes a HeadBlockHash that is a block between the actual PoS head and the transition payload S times, waiting for the client to sync each time

simulators/ethereum/engine: Enhance Post-Merge Sync Test

---

simulators/ethereum/engine/main.go

Updates the maximum difference of the `issued-at` drift difference to 60 seconds, according to this [spec PR](https://github.com/ethereum/execution-apis/pull/256).

simulators/ethereum/engine: Update Max Drift Seconds to Spec

---

simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/teststruct.go

Adds verification and fixes existing verifications of LatestValidHash in all `engine_newPayloadV1` calls.
According to https://github.com/ethereum/execution-apis/pull/254, this line is not verified by any hive tests yet:
> `null` if client software cannot determine the ancestor of the invalid 
In the context of an `INVALID` payload.
Test now prints the calling file/line on failure of any "Expect*" function.

simulators/ethereum/engine: Update/Verify LatestValidHash in more tests

---

simulators/ethereum/engine/enginetests.go
simulators/ethereum/engine/helper.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/mergetests.go
simulators/ethereum/engine/testenv.go

- Create different types of transactions every time a new transaction is requested by the test case (Legacy or 1559)
- Add tests for specific types of corruption on a 1559 type transaction
- Add tests to verify that payloads that include transactions with incorrect Chain ID are rejected
- Add test to verify that transactions with incorrect Chain ID are not included in the payload creation process

simulators/ethereum/engine: Add 1559 Transaction Creation to Tests

---

simulators/ethereum/engine/main.go

- Simple change to the suite names to make it more clear in the https://hivetests2.ethdevops.io/ page that these suites are part of the Engine simulator, since previously these were all part of the single engine test suite, it currently looks like the number of tests decreased.
@fjl

simulators/ethereum/engine: Change Suite Names

---

simulators/ethereum/engine/suites/engine/tests.go

- Nethermind removes peers that does not have the finalized blockhash.
- This causes this test to fail because the secondary client does not have the final block which is also set as the finalized blockhash.
- Finalized blockhash are also suppose to be at least 32 block behind head AFAIK.

Do not set finalized blockhash on invalid missing ancestor reorg via sync test

---

clients/erigon/erigon.sh

With https://github.com/ledgerwatch/erigon/pull/4890, `--engine.addr` was renamed to `--authrpc.addr` in Erigon.
This change also removes `--experimental.overlay` since that's the default now.

Erigon flag engine.addr was renamed to authrpc.addr

---

simulators/ethereum/engine/Dockerfile
simulators/ethereum/engine/client/node/node.go
simulators/ethereum/engine/suites/transition/tests.go
simulators/ethereum/engine/test/env.go

- Change TTD values of gossip tests to make the height of the TTD-reaching block more consistent
- Fix verification of the gossiped block count
- Add tests where the height difference between the common ancestor and the re-org head is greater than 1
- Verify that the node actually mines the expected number of terminal blocks
- Directly use ethash to mine the blocks instead of relying on the miner module; This is done in order to not be affected by some clients that send back a newly mined block to the client where they originally received it from, which caused an internal re-org that messed up with the mining of several terminal blocks
~Some clients are sending back the newly mined block as NewBlockMsg to the `PoW Producer`.
This results in the `PoW Producer` thinking it's out of sync …

simulators/ethereum/engine: Fix Gossip Test Verification

---

simulators/ethereum/engine/suites/sync/tests.go

- Simple change on sync tests to poll again `newPayload` to the client for some of the clients to properly sync

simulators/ethereum/engine: Send `newPayload` again on sync test

---

simulators/ethereum/engine/suites/sync/tests.go

Fix only fast sync config is being run.
Its the closure in a loop thingy. https://stackoverflow.com/questions/26692844/captured-closure-for-loop-variable-in-go
Confirmed archive mode is run when expected.

simulators/ethereum/engine: fix running tests with multiple syncmodes

---

simulators/ethereum/engine/helper/helper.go

The last block is not accounted for.
Confirmed test can pass and TTD is set correctly.

simulators/ethereum/engine: fix wrong TD calculation

---

simulators/ethereum/engine/client/node/node.go
simulators/ethereum/engine/clmock/clmock.go

- Tests that mine PoW blocks during runtime now will get a different coinbase each time to be able to test multiple terminal block with different stateRoots

simulators/ethereum/engine: Randomize Coinbase on Mined Terminal Blocks

---

simulators/ethereum/rpc-compat/Dockerfile
simulators/ethereum/rpc-compat/README.md

This just adds some brief documentation about running the simulator and links to the documentation on generating test fixtures.

simulators/ethereum/rpc-compat: add documentation

---

clients/lighthouse-bn/Dockerfile
clients/lighthouse-bn/lighthouse_bn.sh

Adds client support for `HIVE_ETH2_SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` setting:
- `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` is set in `config.yaml`
- `--safe-slots-to-import-optimistically` is set as parameter to the same value

clients/lighthouse-bn: Add Optimistic Sync Options + Trusted Peers with Static Keys

---

clients/prysm-bn/prysm_bn.sh

- Change deprecated parameter `--http-web3provider` in favor of `--execution-endpoint`

clients/prysm-bn: Update Execution Endpoint Parameter

---

simulators/ethereum/engine/client/node/node.go
simulators/ethereum/engine/helper/block.go
simulators/ethereum/engine/suites/transition/tests.go

- Introduce tests `Syncing on an Invalid Terminal Execution`, described here: https://github.com/txrx-research/TestingTheMerge/blob/main/tests/transition.md (`Syncing with the chain where terminal block is invalid with respect to EE`), where the client is delivered a `newPayload(P1)` and `forkchoiceUpdated(P1)`, and `P1` is built on top of an unknown terminal block that reaches the Terminal Total Difficulty but it's an invalid block due to one of these characteristics
- `difficulty` number in the block header is incorrect according to the ethash consensus mechanism
- Sealed `mixHash` in the block header is incorrect according to the ethash consensus mechanism
- Sealed `nonce` in the block header is incorrect according to the ethash consensus mechanism
Please suggest further modes of …

simulators/ethereum/engine: Syncing on an Invalid Terminal Block (Invalid Execution)

---

simulators/eth2/engine/engineapi.go
simulators/eth2/engine/helper.go
simulators/eth2/engine/main.go
simulators/eth2/engine/nodes.go
simulators/eth2/engine/prepared_testnet.go
simulators/eth2/engine/running_testnet.go
simulators/eth2/engine/scenarios.go
simulators/eth2/engine/verification.go

- Fixes optimistic sync tests by properly waiting until the beacon node becomes optimistic, by querying `execution_optimistic` property from the block in the REST API
- Refactors/cleans up `testnet` code to allow startup/shutdown of a client later during the test
- Introduces test `No viable head due to optimistic sync` from https://github.com/txrx-research/TestingTheMerge/blob/main/tests/engine-api.md
Requires: #604 ~#636~
Supersedes: #631
cc @zilm13 @mkalinin

simulators/eth2/engine: Fix Optimistic Sync Tests + Refactor Allow Client Restarts + No Viable Head Test Case

---

simulators/eth2/engine/running_testnet.go
simulators/eth2/engine/scenarios.go

- Fixes an issue with some of the tests where the test expected that the finalized root included in the checkpoints included an execution payload, and it could be the case where the finalized beacon block happened before the first actual block containing an execution payload.
- Fix is to wait until the finalized root contains an execution payload to be able to verify the `finalized` label more properly.

simulators/eth2/engine: Fix Execution Finality Verification

---

simulators/eth2/engine/prepared_testnet.go
simulators/eth2/testnet/prepared_testnet.go

- Fix the execution client node type to be a full node: All tests were failing because Geth was entering snap sync and rejecting `engine_newPayloadV1` calls, even when the payload was created by the same node itself.

simulators/eth2/testnet,engine: Fix Nodetype

---

simulators/eth2/engine/main.go
simulators/eth2/engine/scenarios.go

- Include test for timeout limits on `engine_newPayloadV1` and `engine_forkchoiceUpdatedV1` calls from the consensus client to the execution client

simulators/eth2/engine: Timeouts test

---

clients/prysm-bn/prysm_bn.sh

- Add prysm parameter `--enable-debug-rpc-endpoints` to be able to query states from the REST API.

clients/prysm-bn: Add enable-debug-rpc-endpoints

---

simulators/ethereum/engine/helper/helper.go
simulators/ethereum/engine/suites/transition/tests.go

- Fixes error where a transaction included in a pre-mined chain could be re-org'd back into the txPool, and when sent again by the simulator it resulted in "already known" error on `eth_sendRawTransaction`

simulator/ethereum/engine: Fix Transaction Already Known Issue

---

clients/erigon/erigon.sh

The `--verbosity` flag has been recently renamed to `--log.console.verbosity` in Erigon.

clients/erigon: Upgrade verbosity flag

---

simulators/ethereum/consensus/main.go

Fixes the following issues:
```
test validation failed for add_d2g0v0_Merge: network `Merge` not defined in ruleset
test validation failed for add_d0g0v0_Merge: network `Merge` not defined in ruleset
test validation failed for add_d3g0v0_Merge: network `Merge` not defined in ruleset
```
https://hivetests.ethdevops.io/?page=v-pills-results-tab&suite=1666953000-4453fd9653a1f707a4edd2efd25af0e7.json

simulators/ethereum/consensus: add merge ruleset

---

clients/erigon/erigon.sh

After https://github.com/ledgerwatch/erigon/pull/5813 Erigon uses embedded light-client CL by default. That mode is not compatible with Hive tests and erigon should be switched back to using external CL.

clients/erigon: Add externalcl flag

---

clients/teku-bn/teku_bn.sh

I think it's a common issue for all CL clients. It's expected by the spec that we have a lot of aggregators and they don't need to subscribe to any extra topics, so when we have just 2 peers, there is a non-zero chance that the other peer is not subscribed to the all attestation subnets, so when first peer is releasing an attestation, another peer sometimes is not able to produce aggregate from it, because it's not subscribed to the topic of this attestation. I have added flag `--p2p-subscribe-all-subnets-enabled` to ensure both peers are listening to the all attestation topics.

clients/teku: Subscribe to all subnets

---

internal/libhive/api.go

When the "environment" field is not included in the client launch configuration,  `env := clientConfig.Environment`(line 224) returns nil and a panic  `assignment to entry in nil map` is raised when we do  `env["HIVE_LOGLEVEL"] = strconv.Itoa(api.env.SimLogLevel)` later (line 236).

internal/libhive: fix assignment to entry in nil map bug

---

simulators/ethereum/engine/client/hive_rpc/hive_rpc.go

Fixes a small nil on the engine tests, which could happen when clients did not return the expected information.

simulators/ethereum/engine: Fix nil exception

---

clients/besu/besu.sh
clients/besu/mapper.jq

This fixes the tests where hive spins up a second instance of besu and sync from the bootnode. Currently node 1 and 2 have the same enode address which stops them from peering with each other 
Linked to [#4747](https://github.com/hyperledger/besu/issues/4747)

clients/besu: add Shanghai fork and fix issue with duplicated node keys

---

README.md
docs/clients.md
docs/simulators.md

README.md, docs: fix typos in documentation

---

clients/nethermind/mkconfig.jq

Adds TERMINAL_BLOCK_HASH and TERMINAL_BLOCK_NUMBER, which fixes interactions with prysm.

clients/nethermind: Use Terminal Block Hash/Number

---

hivesim/testmatch.go
hivesim/testmatch_test.go

For #688, but this doesn't fully implement it. Case-insensitive matching will start working after upgrading the hivesim dependency in simulators.

hivesim: make test matching case insensitive

---

simulators/ethereum/engine/main.go
simulators/ethereum/engine/suites/withdrawals/tests.go

Changes on `simulators/ethereum/engine/withdrawals`:
- Removes Clique from config
- Difficulty set to 0 on genesis
- Sets TTD to 0
- Removes ExtraData from the genesis block
Waiting on @jochem-brouwer to see if this fixes some of the issues on EthJS

simulators/ethereum/engine: Remove PoW config from withdrawals

---

simulators/ethereum/graphql/testcases/14_eth_getBlock_byHash.json
simulators/ethereum/graphql/testcases/16_eth_getBlock_byNumber.json
simulators/ethereum/graphql/testcases/20_eth_getBlockTransactionCount_byNumber.json
simulators/ethereum/graphql/testcases/40_eth_syncing.json

For graphql use long for timestamp and remove two SyncState fields.
A couple of spec changes occured since these tests were created.
* `timestamp` became a long - https://github.com/ethereum/execution-apis/blob/main/schema.graphqls#L109
* `SyncState` does not have `pulledStates` and `knownStates` as these were implementation details of Fast Sync. https://github.com/ethereum/execution-apis/blob/main/schema.graphqls#L400-L411

Align GraphQL tests with current spec

---

simulators/ethereum/engine/suites/engine/tests.go

See https://github.com/ethereum/execution-apis/pull/338

 simulators/ethereum/engine: INVALID_BLOCK_HASH is deprecated in Shanghai

---

cmd/hiveview/assets/lib/app-index.js
cmd/hiveview/assets/lib/app-suite.js
cmd/hiveview/assets/lib/app-viewer.js
cmd/hiveview/assets/lib/app.css
cmd/hiveview/assets/lib/viewer.css
cmd/hiveview/assets/viewer.html

This fixes a few small issues I noticed after deploying the new viewer UI to hivetests.ethdevops.io.

cmd/hiveview: small UI improvements

---

cmd/hiveview/assets/index.html
cmd/hiveview/assets/lib/app-index.js
cmd/hiveview/assets/lib/app-suite.js
cmd/hiveview/assets/lib/app-viewer.js
cmd/hiveview/assets/lib/app.css
cmd/hiveview/assets/lib/app.js
cmd/hiveview/assets/lib/utils.js
cmd/hiveview/assets/lib/viewer.css

Another round of fixes for minor issues in the hiveview UI.

cmd/hiveview: fixes for some UI issues

---

clients/nimbus-bn/Dockerfile
clients/nimbus-el/Dockerfile
clients/nimbus-vc/Dockerfile

Changes:
- Accept a branch argument, so now hive can be called as, e.g.:
```
--clients nimbus-bn_log-withdrawals-discrepancy
```
and the git branch `log-withdrawals-discrepancy` will be used to compile the client. Default is `unstable`.
- Use `--recurse-submodules` on the `git clone` command so the `make` command doesn't need to fetch the submodules.
- `NPROC` is now dynamic.
@tersec

clients/nimbus: clean Dockerfile, accept branch arg

---

simulators/ethereum/engine/suites/withdrawals/README.md
simulators/ethereum/engine/suites/withdrawals/tests.go

Adds a test that verifies `engine_getPayloadBodiesByRangeV1` and `engine_getPayloadBodiesByHashV1` behavior after client syncs to a given canonical chain.

simulators/ethereum/engine: test using getPayloadBodiesByRange/Hash after client sync

---

simulators/eth2/common/spoofing/beacon/beacon_verification.go
simulators/eth2/withdrawals/scenarios.go

Adds a library to detect Engine API calls coming from the beacon client using expired endpoints.
E.g. `engine_newPayloadV1` or `engine_forkchoiceUpdatedV1` containing `timestamp >= ShanghaiTime`.
Code can be easily reused for future upgrades.
Also is added the verification of these expired endpoints on all withdrawals testnet tests, and correctly detects nimbus sending an expired endpoint:
```
FAIL: received directive using expired endpoint engine_forkchoiceUpdatedV1: timestamp 1676055587 >= 1676055587
```
@mkalinin

simulators/eth2/common,withdrawals: Verify Engine API Calls from Beacon Client

---

clients/ethereumjs/ethereumjs.sh

This updates the `ethereumjs.sh` script for the EthereumJS client toadd support for loading predefined blockdata from `chain.rlp`.  In conjunction with the latest version of the EthereumJS client, this should greatly expand the scope of what hive tests our client passes.
cc @g11tech for confirmation

Add support for loading chain.rlp to ethereumjs

---

clients/besu/besu.sh

Reverse the logic to deploy clique key to bootnode only. 
This commit https://github.com/ethereum/hive/commit/104c1851ce7890a605de2b9123835074d7c14ff3 introduced an additional check to prevent deploying the same private key to a second node. Accidentally ended up stopping the deployment of the key for the first node which prevents besu from mining a block using clique and broke a couple of the RPC suite tests.
Please kindly review that and let me know if there's any additional changes required.
This change  has been tested running hive locally and fixes the RPC suite. Didn't detect any new regression

clients/besu: fix clique mining

---

clients/lodestar-bn/lodestar_bn.sh

Lodestar start script contained an erroneously hard-coded log level of `DEBUG`.

clients/lodestar-bn: Fix Log Level

---

simulators/eth2/common/clients/execution.go
simulators/eth2/common/testnet/environment.go
simulators/eth2/common/testnet/prepared_testnet.go
simulators/eth2/common/testnet/running_testnet.go

Adds an optional proxy callback that can log all Engine API calls that the CL makes to the EL.

simulators/eth2/common: Add option to log all engine api calls

---

simulators/eth2/common/clients/beacon.go
simulators/eth2/common/go.mod
simulators/eth2/common/go.sum
simulators/eth2/withdrawals/go.mod
simulators/eth2/withdrawals/go.sum
simulators/eth2/withdrawals/scenarios.go

- Update `eth2api` to version that sets `Content Type` on requests, fixes nimbus and lodestar tests

simulators/eth2/common,withdrawals: Update `eth2api` to fix some clients on bls-to-exec-changes tests

---

simulators/eth2/common/clients/beacon.go
simulators/eth2/common/clients/execution.go
simulators/eth2/common/clients/validator.go
simulators/eth2/common/config/consensus/genesis.go
simulators/eth2/common/config/execution/execution_config.go
simulators/eth2/withdrawals/helper.go
simulators/eth2/withdrawals/scenarios.go
simulators/eth2/withdrawals/specs.go

- Fixes obtaining the beacon state from prysm, which only supports `/eth/v2/debug/beacon/states/{state_id}` where `state_id` is a slot number
- Fix Capella genesis tests by including the execution genesis as the previous execution payload header in the genesis beacon state
- Fix tests where withdrawals were not noticeable because of a decreasing balance (below the minimum withdraw balance of `MAX_EFFECTIVE_BALANCE`)

simulators/eth2/withdrawals: Withdrawals Tests Fixes

---

hivesim/hive.go
hivesim/testapi.go
internal/fakes/container.go
internal/libdocker/container.go
internal/libhive/api.go
internal/libhive/dockerface.go
internal/libhive/testmanager.go

Allows hive to pause/unpause clients by using docker api container pausing feature (https://docs.docker.com/engine/api/v1.23/#pause-a-container).
Useful for beacon client tests since these rely on wall clock to construct the chain, and this introduces a nice test condition for when the client is late to produce blocks when it has to.

hivesim,libhive: add API to pause/unpause client containers

---

simulators/ethereum/engine/client/hive_rpc/hive_rpc.go

Client construct was sending `eth_` requests to engine API port, which not all clients support because it's not required, and this PR changes this to send all requests to the default Eth RPC port (8545).
Also affects `pyspec` simulator.

simulators/ethereum/engine: send `eth_` requests to port 8545

---

clients/ethereumjs/Dockerfile
clients/ethereumjs/ethereumjs.sh

Updates git branch to `develop-v7`.
Also fix minor issue with the block producer account unlock file.
cc @jochem-brouwer

clients/ethereumjs: Update branch

---

simulators/ethereum/pyspec/Dockerfile

Adds a simple comment for instructions on how to run locally generated fixtures.
@spencer-tb

simulators/ethereum/pyspec: Comment Dockerfile to run local fixtures

---

clients/besu/besu.sh

Bonsai is the recommended data-storage-format for public network in Besu. It isn't default though. Besu would like to have hive running using bonsai.

clients/besu: add --data-storage-format=BONSAI 

---

simulators/ethereum/engine/suites/withdrawals/README.md
simulators/ethereum/engine/suites/withdrawals/tests.go
simulators/ethereum/engine/test/expect.go

- Adds test where the simulator makes numerous requests of GetPayloadBodiesByRange and GetPayloadBodiesByHash in parallel
Related issue: https://github.com/ledgerwatch/erigon/issues/7172
Confirmed Erigon after PR https://github.com/ledgerwatch/erigon/pull/7199 passes this test now.

simulators/ethereum/engine: Parallel getPayloadBodies Test

---

clients/erigon/erigon.sh

After https://github.com/ledgerwatch/erigon/pull/7349 the `--externalcl` flag is not supported anymore (the external CL mode is the default now)

clients/erigon: --externalcl flag is not supported anymore

---

clients/nethermind/Dockerfile
clients/nethermind/mapper.jq

Adds support for `HIVE_CANCUN_TIMESTAMP` environment variable.
Also add more args into the Dockerfile to make it easier to manually change the docker image source.
cc @MarekM25

clients/nethermind: Cancun support

---

clients/go-ethereum/Dockerfile
clients/go-ethereum/geth.sh
clients/go-ethereum/mapper.jq
simulators/eth2/engine/Dockerfile
simulators/ethereum/engine/Dockerfile

Geth PoW mining and real verification, and as a result many of the utilities used in tests such as makecache makedag etc.
The `--fakepow` flag is also removed. Now a merge-ready network is required and in that case a PoW fake verifier will be available. To trigger this we set `"terminalTotalDifficultyPassed": true`.
https://github.com/ethereum/go-ethereum/pull/27178

clients/go-ethereum: remove deprecated PoW

---

clients/nethermind/mapper.jq
clients/nethermind/nethermind.sh

Simply adds `excessDataGas` to the genesis field within `clients/nethermind/mapper.jq`, alongside an `echo` command within `clients/nethermind/nethermind.sh` to match the logging of other clients.

clients/nethermind: Add excessDataGas to genesis mapper.

---

simulators/ethereum/pyspec/main.go
simulators/ethereum/pyspec/runner.go
simulators/ethereum/pyspec/types.go

This fixes https://github.com/ethereum/hive/issues/774. It also adds support for `-sim.limit`
Example:
```
user@debian-work:~/workspace/hive$ ./hive --sim ethereum/pyspec --client go-ethereum_latest  --sim.loglevel 3 --docker.output -sim.limit=pyspec/invalid_blob_txs
```
```
INFO[05-05|14:14:41] running simulation: ethereum/pyspec 
INFO[05-05|14:14:42] hiveproxy started                        container=1f6d4f6eb159 addr=172.17.0.2:8081
INFO[05-05|14:14:42] API: suite started                       suite=0 name=pyspec
INFO[05-05|14:14:42] API: test started                        suite=0 test=1 name=pytest_fixture_runner
[34c50e31] parallelism set to: 1
[34c50e31] file root directory: /fixtures/
[34c50e31] skip eips/eip3651/warm_coinbase_call_out_of_gas
[34c50e31] skip …
```

sim/pyspec: bubble error

---

clients/besu/besu.sh

Currently besu fails on some of the rcp-compat tests because the JSON RPC DEBUG API is not enabled

Enable DEBUG API used by rcp-compat suite

---

clients/go-ethereum/Dockerfile
clients/go-ethereum/Dockerfile.git
clients/go-ethereum/Dockerfile.local
docs/clients.md
docs/commandline.md
go.mod
go.sum
hive.go
internal/fakes/builder.go
internal/libdocker/builder.go
internal/libhive/dockerface.go
internal/libhive/inventory.go
internal/libhive/inventory_test.go
internal/libhive/run.go
internal/libhive/run_test.go
internal/libhive/testmanager.go

Allows specifying a `--client-file` parameter which shall be read in YAML or JSON format and must contain the client build modifiers.
Supported modifiers:
- client: Name of the client, eg: besu, go-ethereum, etc
- dockerfile: Dockerfile to use. E.g. using `dockerfile: git` will build using `Dockerfile.git` instead of the default `Dockerfile`
- build_args: Build arguments passed to the docker build engine to use when building the image
Supported docker image build arguments depend on the client and the docker image being used, but common client build arguments are:
- tag: Git branch or docker tag name to use during build process.
- github: The repository containing the client source code (for git-based Dockerfiles)
- baseimage: The client image name on DockerHub.
Also adds example …

libhive: client build args and alternative dockerfiles

---

clients/nethermind/Dockerfile
clients/nethermind/Dockerfile.git
clients/nethermind/Dockerfile.local

Requires: #767.
Adds `clients/nethermind/Dockerfile.git` to build Nethermind from any git branch.
Adds `clients/nethermind/Dockerfile.local` to build Nethermind from a local directory.

clients/nethermind: Dockerfile support to build Nethermind from git or locally

---

clients/erigon/Dockerfile
clients/erigon/Dockerfile.git
clients/erigon/Dockerfile.local

Requires: https://github.com/ethereum/hive/pull/767.
Adds clients/erigon/Dockerfile.git to build Erigon from any git branch.
Adds clients/erigon/Dockerfile.local to build Erigon from a local directory.

clients/erigon: Dockerfile support to build Erigon from git or locally.

---

clients/ethereumjs/Dockerfile
clients/ethereumjs/Dockerfile.local

Requires: https://github.com/ethereum/hive/pull/767.
Updates clients/ethereumjs/Dockerfile.
Adds clients/ethereumjs/Dockerfile.local to build Ethereumjs from a local directory.

clients/ethereumjs: Dockerfile support to build Ethereumjs locally

---

clients/go-ethereum/Dockerfile.git

Fixes a typo when the built binary is copied in the Dockerfile.git for go-ethereum.

clients/go-ethereum: fix typo in git dockerfile

---

simulators/ethereum/engine/go.mod
simulators/ethereum/engine/main.go
simulators/ethereum/engine/suites/exchange_capabilities/tests.go
simulators/ethereum/go.work.sum

Changes the `engine-exchange-capabilities` test suite to run with proper fork configuration, with and without the fork being already active.
Currently only Shanghai, and Cancun should be added in #759

simulators/ethereum/engine: Per-fork Exchange Capabilities  Tests

---

clients/nethermind/mapper.jq

Adds `dataGasUsed` to the genesis mapper of Nethermind, for it to be able to start from Cancun fork.

clients/nethermind: add dataGasUsed to mapper

---

hive.go
internal/libhive/inventory.go

This change makes it so we can have all client definitions in one file, and then select the ones that should run.
```
./hive -client-file configs/4844.yaml -client nethermind -sim ethereum/engine
```

hive: make -client filter the list given in YAML file

---

clients/ethereumjs/mapper.jq

Fixes mapper of the Ethereum JS client to remove all fields with null values.

clients/ethereumjs: Fix mapper

---

clients/ethereumjs/Dockerfile.local
clients/ethereumjs/ethereumjs.sh

Hive keeps trying to connect to RPC, but we never get those messages, and need to listen to `0.0.0.0`. 
(This temporarily also disables the websockets, since it throws if we enable them)
Also updates the local dockerfile: syntax fix + better local caching (install all apt stuff once instead of every time).

EthereumJS: fix client timeout on startup

---

configs/cancun.yaml
go.sum
simulators/ethereum/go.work.sum
simulators/ethereum/pyspec/Dockerfile
simulators/ethereum/pyspec/gen_bh.go
simulators/ethereum/pyspec/gen_enp.go
simulators/ethereum/pyspec/go.mod
simulators/ethereum/pyspec/go.sum
simulators/ethereum/pyspec/runner.go
simulators/ethereum/pyspec/types.go

This PR contains a few small tweaks for the pyspec simulator such that it runs the current execution-spec-tests fixtures correctly.

simulators/ethereum/pyspec: Fixes for Cancun Devnet 8

---

clients/go-ethereum/Dockerfile.git
clients/nethermind/Dockerfile.git

When building clients from the `Dockerfile.git` files it doesn't show the what branch is being used for geth and nethermind within the build log.
This PR addresses the latter for easier debugging.

clients/go-ethereum,nethermind: Add logging of git branch to Dockerfile.git

---

simulators/ethereum/pyspec/gen_enp.go
simulators/ethereum/pyspec/runner.go
simulators/ethereum/pyspec/types.go

Fixes current false positive and false negative cases for fork transition tests. 
Engine API error codes have been added to the fixtures such they can be parsed within the simulator:
https://github.com/ethereum/execution-spec-tests/pull/248
If an error code exists within a test case the simulator will now check that it matches the expected response from the Engine API.

simulators/ethereum/pyspec: Add Engine API error code checks for erroneous test cases

---

simulators/ethereum/pyspec/Dockerfile

Updates github.com/ethereum/execution-spec-tests fixtures version from `v1.0.1` to `v1.0.2`.
Release notes here: https://github.com/ethereum/execution-spec-tests/releases/tag/v1.0.2

simulators/ethereum/pyspec: Update fixtures version

---

clients/go-ethereum/Dockerfile.local

There are two issues in the `Dockerfile.local` for geth.
1) the `WORKDIR` is set as an absolute path, but it should be relative
2) the container doesn't have the appropriate dependencies to build geth

clients/geth: fix local dockerfile issue

---

simulators/ethereum/engine/clmock/clmock.go
simulators/ethereum/engine/suites/cancun/config.go
simulators/ethereum/engine/suites/cancun/steps.go
simulators/ethereum/engine/suites/cancun/tests.go

Adds the following ForkID tests:
- Genesis timestamp = 0, Shanghai at 0, Cancun at 0 -> peer at Block 0
- Genesis timestamp = 0, Shanghai at 0, Cancun at 1 -> peer at Block 0
- Genesis timestamp = 0, Shanghai at 0, Cancun at 1 -> peer at Block 1
- Genesis timestamp = 1, Shanghai at 1, Cancun at 1 -> peer at Block 0
- Genesis timestamp = 1, Shanghai at 1, Cancun at 2 -> peer at Block 0
- Genesis timestamp = 1, Shanghai at 1, Cancun at 2 -> peer at Block 1
cc @jochem-brouwer @lightclient @spencer-tb

simulators/ethereum/engine: Add more ForkID tests

---

simulators/ethereum/engine/globals/globals.go
simulators/ethereum/engine/suites/cancun/config.go
simulators/ethereum/engine/suites/withdrawals/tests.go

Brings together the configuration elements of the different forks into a single method.
Fixes an issue when running `ExchangeCapabilities` tests of an improperly configured genesis.

simulators/ethereum/engine: Coalesce fork configs

---

clients/erigon/Dockerfile.git

Fixes an issue with Erigon not building properly in hivecancun host due to usage of the latest go version.

clients/erigon: Specify golang versioned image

---

configs/cancun.yaml

Changes Besu's branch to the one to be used on devnet-8 runs.

configs/cancun: Change besu branch

---

cmd/hiveview/assets/index.html
cmd/hiveview/assets/lib/app-index.js
cmd/hiveview/assets/lib/utils.js

This adds more differentiated column filters to `hiveview` for easier selection of a test suite or a client and generally a better overview what is available. This is not meant to replace but complement the existing global search functionality.
Following additions:
- `Date` filter: Filters for "Today", "Yesterday", "x days ago"
- `Suite` filter: Collects the different suites for choice
- `Client` filter: Collects the single clients for choice (I have decided to *not* include combined versions for better overview, this can still be done by fulltext search though)
- `Status` filter: Filter for "SUCCESS", "FAIL" and "TIMEOUT"
Side note on the date filter: it would have been nice to also be able to filter by a range of dates, e.g. a period of a whole week. However this is substantially more …

cmd/hiveview: Add Column Filters

---

simulators/ethereum/engine/client/engine.go
simulators/ethereum/engine/client/node/node.go
simulators/ethereum/engine/clmock/clmock.go
simulators/ethereum/engine/globals/globals.go
simulators/ethereum/engine/helper/customizer.go
simulators/ethereum/engine/suites/cancun/config.go
simulators/ethereum/engine/suites/cancun/steps.go
simulators/ethereum/engine/suites/cancun/tests.go
simulators/ethereum/engine/test/expect.go

Addresses missing GetPayloadV2/V3 and ForkchoiceUpdatedV2/V3 tests at fork time, described in comment: https://github.com/ethereum/hive/issues/810#issuecomment-1672182427

simulators/ethereum/engine: Add incorrect engine versions tests

---

configs/cancun.yaml

Updates besu branch to: [Gabriel-Trintinalia/besu@add-decode-type-to-transaction-decoder](https://github.com/Gabriel-Trintinalia/besu/tree/add-decode-type-to-transaction-decoder)
cc @parithosh @Gabriel-Trintinalia let me know when this should be rolled back

configs/cancun: Besu update

---

clients/reth/mapper.jq
clients/reth/reth.sh

Adds cancun fork in mapper and documents shanghai / cancun timestamps in `reth.sh`

clients/reth: add cancun fork in mapper

---

clients/erigon/Dockerfile.git

Fixes the `Dockerfile.git` on some tests where it needed to fetch the enode because curl was not installed.

clients/erigon: Fix `Dockerfile.git`

---

clients/reth/Dockerfile.git
clients/reth/Dockerfile.local

Similar to the following PRs: https://github.com/ethereum/hive/pull/782, https://github.com/ethereum/hive/pull/779, https://github.com/ethereum/hive/pull/772 & https://github.com/ethereum/hive/pull/785
We can now build reth from git assuming the following `configs/reth.yaml` file exists: 
```yaml
- client: reth
nametag: reth-git
dockerfile: git
build_args:
github: paradigmxyz/reth
tag: main
```
Similarly, it can be built locally assuming a local copy of reth is within `clients/reth/<reth>`:
```yaml
- client: reth
nametag: reth-local
dockerfile: local
```
Using the following command to assert that the appropriate config file:
```bash
./hive --sim <simulation> --client-file configs/reth.yaml --client reth
```

clients/reth: Dockerfile support to build Reth from git or locally

---

clients/besu/besu.sh

Besu has implemented a new txpool format and will not start if any legacy flag is present.

clients/besu: sh - Remove legacy option from startup flags

---

simulators/ethereum/pyspec/Dockerfile

Updates execution-spec-tests version, which includes the same beacon root contract address as the existing engine-api tests

simulators/ethereum/pyspec: update execution-spec-tests

---

cmd/hiveview/assets/index.html
cmd/hiveview/assets/lib/app-index.js

This is an alternative/extension of #862. When selecting a column filter in the table header, it will now be persisted to the URL. So if you want a page that shows only a specific client, you can get it by bookmarking the URL.

cmd/hiveview: persist column filters in URL

---

simulators/ethereum/engine/main.go

I applied the same parallelization technique as in the `ethereum/consensus` simulator.
Before parallelization, we see running some blob tests takes XXX:
```console
time go run . --client-file clients.yaml --sim ethereum/engine --sim.limit "engine-cancun/blob"
...
4.18s user 6.83s system 3% cpu 5:23.29 total
```
After parallelization, we see running good improvement with blob tests taking only XXX:
```console
time go run . --client-file clients.yaml --sim ethereum/engine --sim.limit "engine-cancun/blob"
...
4.06s user 6.48s system 5% cpu 2:59.13 total
```
In both examples, the simulator docker image is compiled, so that shouldn't play into the difference.

simulators/ethereum/engine: run tests in parallel

---

simulators/ethereum/engine/config/fork.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/suites/engine/misc.go
simulators/ethereum/engine/suites/engine/tests.go
simulators/ethereum/engine/suites/withdrawals/tests.go

Adds a single test where a pre-merge (by block number) fork is not zero. 
Catches https://github.com/ethereum/go-ethereum/issues/28134 (on v1.13.0) and passes on latest master.

simulators/ethereum/engine: Add London non-zero-number test

---

simulators/ethereum/engine/config/cancun/genesis.go

Looks like in #884 there was a small issue where `0x` prefix was added to the code. This is not accepted by `common.Hex2Bytes`, which fails silently when the prefix exists.

simulators/ethereum/engine: rm 0x prefix on 4788 code

---

clients/erigon/erigon.sh

Erigon now has a built-in spam protector for blob txs, this flag would increase the count of allowed blobs per account from the default 48 to a 1000

clients/erigon: Increase allowed blobcount in remote txs

---

simulators/ethereum/engine/go.mod
simulators/ethereum/engine/go.sum
simulators/ethereum/pyspec/go.mod
simulators/ethereum/pyspec/go.sum

Since the beacon root is hard coded in the `params/protocol_params.go` in geth, the `1.13.1` release is out of date and building invalid blocks for the "Invalid Ancestors" test suite. This PR points to the `lightclient/devnet-9` branch with the updated commit until https://github.com/ethereum/go-ethereum/pull/28205 is merged and a new release is issued.

simulators/ethereum/engine: use replaced version of geth with updated beacon root

---

simulators/ethereum/engine/suites/cancun/tests.go
simulators/ethereum/engine/suites/engine/invalid_payload.go
simulators/ethereum/engine/suites/engine/misc.go

-  Pre-Merge Fork > 0: Post-merge forks are now all happening on block 1 for consistency
- Invalid Versioned Hashes verification fixes

simulators/ethereum/engine: Engine API Test Fixes

---

clients/besu/Dockerfile.git
clients/besu/Dockerfile.local

intermittent startup errors reported using older docker base image.
Aiming to use the same base image we use for building besu elsewhere. 
See https://github.com/hyperledger/besu/pull/5951

clients/besu: use ubuntu base image and install java

---

simulators/ethereum/engine/clmock/clmock.go
simulators/ethereum/engine/helper/customizer.go
simulators/ethereum/engine/helper/tx.go
simulators/ethereum/engine/suites/cancun/steps.go
simulators/ethereum/engine/suites/cancun/tests.go
simulators/ethereum/engine/suites/engine/payload_id.go
simulators/ethereum/engine/suites/engine/tests.go
simulators/ethereum/engine/suites/engine/versioning.go

- Small fix to the setup of the generic versioning tests
- Fixes the tx replacement that affected one Cancun test
- Fixed the Unique ID test for the beacon root attribute
- Added a per-client map for payload IDs (allows collisions between clients for some clients that use a simple counter e.g. Erigon)

simulators/ethereum/engine: Fix several tests

---

simulators/ethereum/engine/suites/engine/invalid_payload.go

Fixes the incomplete transactions tests on Cancun, since the transaction is removed, and the transaction is a blob transaction, the client can return `nil` in the latest valid hash field per spec because the `versionedHashes` are incorrect.

simulators/ethereum/engine: Fix incomplete transactions test

---

clients/nimbus-el/enode.sh

Most/all EL clients seem to use admin_nodeInfo so we adjusted this in nimbus-eth1.
See also https://github.com/status-im/nimbus-eth1/pull/1799

Use admin_nodeInfo instead of net_nodeInfo in nimbus enode.sh

---

simulators/ethereum/engine/helper/customizer.go
simulators/ethereum/engine/helper/tx.go
simulators/ethereum/engine/suites/cancun/tests.go
simulators/ethereum/engine/suites/engine/invalid_payload.go
simulators/ethereum/engine/suites/engine/tests.go

- Invalid payload fields that can be detected by static check before sync are now optional, therefore `INVALID` and `SYNCING` can be accepted for payloads that can be detected to be invalid even before sync
- Invalid payloads with an invalid transaction now use more plausible values. E.g. `nonce < 2**64-1`, `gasLimit > 0`
- `ForkchoiceUpdatedV2 then ForkchoiceUpdatedV3 Valid Payload Building Requests` now does not send blob transactions before Cancun fork.
@lightclient @g11tech @acolytec3  @MarekM25 @marcindsobczak @yperbasis @jflo

simulators/ethereum/engine: Fixes from interop meeting

---

clients/erigon/mapper.jq
clients/go-ethereum/mapper.jq
clients/reth/mapper.jq
simulators/ethereum/engine/config/fork.go
simulators/ethereum/engine/config/genesis.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/suites/engine/misc.go
simulators/ethereum/engine/suites/engine/tests.go

Adds an update to the test here: https://github.com/ethereum/hive/pull/867, where a pre-merge fork is non-zero.
Previously, this test would start by loading a genesis config where the pre-merge fork (London) occured at the same block (block 1) as the post merge fork under test.
Now the genesis config starts with a pre-merge fork (London) and merge fork (Paris) both occuring on block 1. Then the post merge-fork under test occurs at block 2.
cc @marioevz @flcl42

simulators/ethereum/engine: Update post-merge forks to activate later in pre-merge test

---

simulators/ethereum/engine/suites/engine/invalid_ancestor.go
simulators/ethereum/engine/suites/engine/tests.go

- Naming in "Invalid Missing Ancestor ReOrg" now does not repeat for some of the tests
- Safe and Finalized hash in re-org tests now always points to 0x00..00

simulators/ethereum/engine: Fix naming, safe/finalized on reorg tests

---

simulators/ethereum/engine/suites/engine/rpc.go

Right now, many of these RPC tests expect clients to return `-39001` if `safe` or `finalized` block is not found. Geth doesn't support custom RPC errors for the `eth` namespace so I really prefer if we just expect an error and be happy if we get either `39001` or `-32000`.

simulators/ethereum/engine: use generic error check for missing block

---

hivesim/hive_test.go
internal/libhive/api.go
internal/libhive/run.go
internal/libhive/testmanager.go

Changes map usages to a list in order to try to preserve the order in which the clients are listed in the client-file.
In simulator `eth2-dencun` there is a new suite that depends on an specific client being launched first before any other client combination ("evil-teku").

libhive: Return client types in the order defined in the client-file

---

cmd/hivechain/output.go

Previously, `hivechain` would output the chain starting with the block after genesis. This makes sense because when we init a client with the genesis file it constructs the genesis block.
This change would be nice to have since anything that was previously consuming `chain.rlp`s from `hivechain` will need to be updated to skip over the genesis block otherwise.

cmd/hivechain: export chain starting after genesis

---

cmd/hivechain/genesis.go

Geth [no longer supports](https://github.com/ethereum/go-ethereum/blob/cd2953567268777507b1ec29269315324fb5aa9c/eth/ethconfig/config.go#L181-L186) PoW networks, so we need to make sure the genesis lists the `ttd` as passed.

cmd/hivechain: write ttd passed to genesis if merged

---

cmd/hivechain/README.md
cmd/hivechain/genesis.go
cmd/hivechain/output.go
cmd/hivechain/output_forkenv.go

Adds a new output mode "forkenv" that has the hive fork configuration variables.

cmd/hivechain: add forkenv output

---

cmd/hivechain/generate.go

Currently preimages is turned off during chain generation. This causes the state dump to fail to output the genesis accounts:
```
WARN [10-20|17:37:46.743] Dump incomplete due to missing preimages missing=19
```

hivechain: track preimages during generation

---

simulators/ethereum/engine/Dockerfile
simulators/ethereum/pyspec/Dockerfile

- Use `golang:1.20-alpine` instead of `golang:1-alpine` as base image to build the simulators, since `golang:1-alpine` now points to `golang:1.21-alpine` and compilation fails in this newer version.

simulators/ethereum/engine,pyspec: Use `golang:1.20-alpine`

---

simulators/ethereum/engine/suites/cancun/tests.go

There are a few bugs within some of the engine-cancun fcu version tests. This PR aims to fix them and add more clarity to the test descriptions. Some fixes are from @jangko within https://github.com/ethereum/hive/pull/930.

simulators/ethereum/engine: Fix engine-cancun fcu version tests

---

clients/besu/besu.sh
clients/erigon/erigon.sh
clients/ethereumjs/ethereumjs.sh
clients/go-ethereum/geth.sh
clients/nethermind/nethermind.sh
clients/nimbus-el/nimbus.sh
clients/reth/reth.sh

Similar to https://github.com/ethereum/hive/pull/923, when debugging more than one test, the genesis config for each test can flood the simulation output making it difficult to debug.
We only log the entire `genesis.json` config when the `HIVE_LOGLEVEL > 3`.

clients: only output full genesis file at high log levels

---

simulators/ethereum/engine/README.md
simulators/ethereum/engine/suites/cancun/tests.go
simulators/ethereum/engine/suites/engine/bad_hash.go
simulators/ethereum/engine/suites/engine/fork_id.go
simulators/ethereum/engine/suites/engine/invalid_ancestor.go
simulators/ethereum/engine/suites/engine/invalid_payload.go
simulators/ethereum/engine/suites/engine/payload_attributes.go
simulators/ethereum/engine/suites/engine/payload_execution.go
simulators/ethereum/engine/suites/engine/payload_id.go
simulators/ethereum/engine/suites/engine/prev_randao.go
simulators/ethereum/engine/suites/engine/reorg.go
simulators/ethereum/engine/suites/engine/suggested_fee_recipient.go

Updates existing engine simulator test names such that they are distinct.
This means they can all be ran seperately whilst debugging.

simulators/ethereum/engine: update test names for distinction

---

simulators/ethereum/engine/suites/engine/reorg.go
simulators/ethereum/engine/suites/engine/tests.go

Adds a re-org test where a tx that was already included in a block is re-org'd back out to the mempool and the client needs to pick it out from the mempool to build the next block.
This hits an issue where besu was building invalid blocks because the tx was not preserving the blobs when it was sent back to the mempool again.
Geth is passing the test.
Nethermind, Erigon and EthereumJS are failing this test because the tx that was re-org'd out is not being included in the next block, so I think it's not making its way back to the mempool for some reason.
```
./hive --client-file ./configs/cancun.yaml --client <client> --sim ethereum/engine --sim.limit "engine-cancun/Transaction Re-Org, Re-Org Back In"
```
@MarekM25 @marcindsobczak @yperbasis @jflo @g11tech @acolytec3

simulators/ethereum/engine: Add test to re-org to mempool and back in

---

simulators/ethereum/engine/suites/engine/reorg.go

Sends the last known block to the CL Mock to the execution client in order for it to be on the expected head.
Previously, the test sent an FcU which overrode what the CL Mock last instructed, which resulted in some clients ending up on the incorrect head (Some clients ignored the directive because an FcU to an ancestor of the current head is optional according to the spec: https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#specification-1).
cc @jochem-brouwer

simulators/ethereum/engine: Minor fix to re-org tests

---

hivesim/hive.go
hivesim/testapi.go

When debugging a single test,
```bash
... --sim.limit engine-cancun/"ForkchoiceUpdatedV2 To Request Shanghai Payload, Zero Beacon Root" --docker.output
```
more often than not the output is flooded with all the tests that are skipped, for example:
```
[4b993452] skipping test "Invalid VersionedHashes Version NewPayload (Cancun) (go-ethereum_cancun-git)" because it doesn't match test pattern engine-cancun/ForkchoiceUpdatedV2 To Request Shanghai Payload, Zero Beacon Root
[4b993452] skipping test "Invalid VersionedHashes Version NewPayload - Syncing (Cancun) (go-ethereum_cancun-git)" because it doesn't match test pattern engine-cancun/ForkchoiceUpdatedV2 To Request Shanghai Payload, Zero Beacon Root
[4b993452] skipping test "Invalid Incomplete VersionedHashes NewPayload (Cancun) …
```

hivesim: only log test and suite skips at high log levels

---

simulators/ethereum/engine/suites/engine/fork_id.go
simulators/ethereum/engine/suites/engine/invalid_ancestor.go

- All Fork ID tests for Paris were failing for each client, due to the addition of this PR: https://github.com/ethereum/hive/pull/901, which added a `mergeNetsplitBlock` to each client mapper.
- Fixed by overriding this value to 0 within the ForkID tests.
- Missing Ancenstor Syncing tests with an invalid state root were failing for the cases that didn't reorg on the canonical chain:
- `Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=False`
- `Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=False`
- Fixed by adding back the engine client before the side chain production.
Found by @flcl42 & @asdacap.

simulators/ethereum/engine: Fix bugs for ForkID and Missing Ancenstor Tests

---

clients/ethereumjs/ethereumjs.sh

We have updated the way the client logs RPC messages. This change ensures that all RPC requests/responses are logged completely (without this, and with the new PR, the client would not none at all).
See https://github.com/ethereumjs/ethereumjs-monorepo/pull/3125

clients/ethereumjs: verbose logging

---

docs/commandline.md
docs/simulators.md
hive.go
internal/libhive/run.go
internal/libhive/testmanager.go

Adds flag `--sim.randomseed <number>` to hive command to pass environment variable `HIVE_RANDOM_SEED` to simulators in order for them to parse and generate a deterministic randomness source.

cmd/hive: Add `--sim.randomseed`

---

simulators/ethereum/engine/clmock/clmock.go
simulators/ethereum/engine/helper/customizer.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/suites/cancun/steps.go
simulators/ethereum/engine/suites/engine/bad_hash.go
simulators/ethereum/engine/suites/engine/forkchoice.go
simulators/ethereum/engine/suites/engine/invalid_ancestor.go
simulators/ethereum/engine/suites/engine/invalid_payload.go
simulators/ethereum/engine/suites/engine/payload_attributes.go
simulators/ethereum/engine/suites/engine/payload_execution.go
simulators/ethereum/engine/suites/engine/reorg.go
simulators/ethereum/engine/suites/engine/suggested_fee_recipient.go
simulators/ethereum/engine/suites/sync/tests.go
simulators/ethereum/engine/suites/withdrawals/tests.go
simulators/ethereum/engine/test/env.go

Adds parsing of `HIVE_RANDOM_SEED` introduced in https://github.com/ethereum/hive/pull/943 in order to be able to deterministically replicate previous runs using the same random seed.
`simulator.log` output now prints the randomness source seed used for a given run, which is basically just `time.Now().Unix()` if no predefined random seed was specified.
Also now each test case has its own unique randomness source in order to make the tests deterministic even when running in parallel.

simulators/ethereum/engine: Add randomness seed input

---

clients/ethereumjs/.dockerignore
clients/ethereumjs/Dockerfile.local
clients/ethereumjs/ethereumjs-local.sh

This PR updates the local dockerfile such that changes to the local monorepo are built much quicker. This diverges from the normal Dockerfile which pulls our latest `master`, and uses `node` on the built version of the client instead of `ts-node` which uses the unbuilt client (but the built other libraries) to speedup this process.

ethereumjs: add faster local test dockerfile

---

clients/lodestar-vc/lodestar_vc.sh

clients/lodestar-vc: add `--builder` flag

---

clients/teku-bn/teku_bn.sh

Adds a rate limit parameter to teku, necessary for it to not rate limit peers based on RPC requests.
@tbenr

clients/teku-bn: Add rate limit parameters

---

simulators/ethereum/engine/go.mod
simulators/ethereum/engine/go.sum
simulators/ethereum/pyspec/go.mod
simulators/ethereum/pyspec/go.sum

Removes `go.mod` replacing of `github.com/ethereum/go-ethereum` and upgrades to `master` branch.

simulators/ethereum/engine,pyspec: Upgrade geth branch

---

configs/cancun.yaml

Removes `lightclient/go-ethereum@devnet-10` from cancun's config file and uses `master` instead.

configs/cancun: Use go-ethereum master

---

clients/erigon/erigon.sh
clients/erigon/mapper.jq
simulators/ethereum/rpc/main.go

- Adding `ws.port` explicitly
- `terminalTotalDifficultyPassed` was hardcoded to `true`, now setting it to env-based, but default to `true`. This is so as to not break existing tests. Later this must be only env-based, and changes to the HIVE env params must be made in specific test suites.

clients/erigon, simulators/ethereum/rpc: patch RPC tests for erigon

---

clients/nethermind/Dockerfile.git
clients/nethermind/Dockerfile.local

- Upgrade Nethermind Dockerfiles to .NET 8, because the client has been already upgraded on master
- May help to bring the client back to the cancun hive tests

clients/nethermind: upgrade to .NET 8

---

simulators/devp2p/Dockerfile
simulators/devp2p/main.go

This is for making the new test suite in https://github.com/ethereum/go-ethereum/pull/28340 work in hive.

simulators/devp2p: add support for new eth tests

---

clients/nethermind/mkconfig.jq

Nethermind recently refactored blob pool to support blob transaction reorgs, introducing an additional flag. We decided to consolidate three blob pool-related flags into one enum. This PR enables support for blob transactions + persistent blob storage + blob transactions reorgs.

clients/nethermind: update TxPool config

---

simulators/ethereum/consensus/main.go
simulators/ethereum/consensus/types.go

Fixes passing the correct non-zero `excessBlobGas` to clients' genesis files.

simulators/ethereum/consensus: Fix `excessBlobGas` genesis

---

simulators/ethereum/engine/suites/cancun/README.md
simulators/ethereum/rpc/README.md

Found two little errors while reading some README files. 
Doesn't require testing or changelog entry.
Have a nice evening.

all: fix some typos in README.md files

---

clients/nethermind/Dockerfile.git

Small fix to force using the correct dotnet sdk docker image, which was producing a failure when trying to build Nethermind from git.

clients/nethermind: Fix Dockerfile.git

---

.circleci/config.yml
.circleci/continue_config.yml
.circleci/rust-simulators.sh

https://github.com/ethereum/hive/pull/976 <- this PR should be reviewed first, or this one can up to the reviewer.
This PR adds a CI to test the rust simulators
Because of the last PR this CI will only run if code is modified in the simulators/portal folder

.circleci: Add CI for rust simulators

---

clients/fluffy/Dockerfile
clients/fluffy/fluffy.sh
clients/trin-bridge/Dockerfile
clients/trin-bridge/trin_bridge.sh
clients/trin-bridge/trin_bridge_version.sh
clients/trin/Dockerfile
clients/trin/trin.sh
clients/trin/trin_version.sh
clients/ultralight/Dockerfile
clients/ultralight/ultralight.sh

This is a PR adding Portal client definitions so we can move portal-hive to hive.

clients: add portal network client definitions

---

clients/reth/mapper.jq

reth does not deserialize `parisBlock` to anything, so this is incorrect. reth is compatible with the geth genesis format, including `mergeNetsplitBlock`, so this changes the mapper back.
Fixes https://github.com/paradigmxyz/reth/issues/6291

clients/reth: fix merge netsplit block in mapper

---

simulators/ethereum/pyspec/Dockerfile
simulators/ethereum/pyspec/runner.go
simulators/ethereum/pyspec/types.go

Updates pyspec to use the latest fixture release, with additional tests and slight format change:
https://github.com/ethereum/execution-spec-tests/releases/tag/v2.1.0

simulators/ethereum/pyspec: Use latest EEST fixture release.

---

clients/prysm-vc/prysm_vc.sh

Changes prysm validator client to use the REST api endpoint instead of gRPC.
Will allow us to use https://github.com/marioevz/blobber
cc @parithosh this might be necessary on the devnets/kurtosis

clients/prysm-vc: Use REST api

---

clients/lodestar-bn/lodestar_bn.sh

Adds a flag that can be enabled on a per-simulator basis to disable peer scoring (e.g. p2p blob gossiping tests).
@g11tech

clients/lodestar-bn: Add optional flag to disable peer scoring

---

clients/erigon/erigon.sh

Sets the snapshots flag to false when running simulations for erigon.
Fixes the existing test failures on [hivecancun](https://hivecancun.ethdevops.io/#client=erigon_cancun-git).

clients/erigon: Configure snapshots flag

---

clients/go-ethereum/geth.sh

Removes the miner gasprice flag for go-ethereum in alignment with the following PR:
https://github.com/ethereum/go-ethereum/pull/28933
Fixes additional test failures on [hivecancun](https://hivecancun.ethdevops.io/#client=go-ethereum_cancun-git).

clients/go-ethereum: Remove miner gasprice flag

---

simulators/ethereum/engine/suites/cancun/tests.go
simulators/ethereum/engine/suites/engine/forkchoice.go
simulators/ethereum/engine/suites/engine/payload_attributes.go
simulators/ethereum/engine/test/spec.go

Fixes issues on tests from changes described on [execution-apis/pull/498](https://github.com/ethereum/execution-apis/pull/498)
Fixes #961
- Change expected error from `INVALID_PARAMS_ERROR` to `INVALID_PAYLOAD_ATTRIBUTES` on following tests:
- ForkchoiceUpdatedV3 To Request Shanghai Payload, Null Beacon Root
- ForkchoiceUpdatedV2 To Request Shanghai Payload, Non-Null Beacon Root
- ForkchoiceUpdatedV2 To Request Cancun Payload, Non-Null Beacon Root
- Expectation of test "Invalid PayloadAttributes, Missing BeaconRoot, Syncing=True" is modified according to point 7 of https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#specification-1, which now strictly specifies that no error should be returned on an invalid payload attributes when the applied forkchoice state is …

simulators/ethereum/engine: Fixes for execution-apis#498

---

simulators/ethereum/engine/suites/engine/payload_attributes.go

Following this PR: https://github.com/ethereum/hive/pull/974
Some clients are passing: `"Invalid PayloadAttributes, Missing BeaconRoot, Syncing=False"` returning the invalid parameters error code -32602, this should be -38003. Although the purpose of the test is to check that the fcu head is updated, the following change adds further verification by additionally expecting the correct error code response.

simulators/ethereum/engine: Expect error code for invalid payload attributes tests

---

clients/lighthouse-bn/lighthouse_bn.sh

Adds reading the `HIVE_ETH2_TRUSTED_PEER_IDS` environment variable which can be set from the simulators in order to add a Peer ID to lighthouse's list of trusted peers.
Required for the devp2p blobs tests.

clients/lighthouse-bn: Add trusted peers env var

---

clients/erigon/erigon.sh

This became necessary because of this test: `Re-Org Back into Canonical Chain, Depth=10, Execute Side Payload on Re-Org`
That uses about 850 blobs in its peak. It can be noted that the default number of blobs allowed in erigon's txpool at the moment is 480.

clients/erigon: Increase blobpool limit in Erigon

---

simulators/ethereum/pyspec/main.go
simulators/ethereum/pyspec/runner.go
simulators/ethereum/pyspec/types.go

- Cleanup to `main.go` and `runner.go`: Refactor some types and add methods directly in the structures where appropriate
- Reads the sync header introduced by https://github.com/ethereum/execution-spec-tests/pull/431
cc @spencer-tb let me know what you think, injecting an empty block to our eest tests might be too much but I'm unsure

simulators/ethereum/pyspec: Refactor, add sync payload verification

---

clients/reth/reth.sh

Reth has a pruner job that locks the database for writing. If that happens, any FCU is skipped. 
Although it's not that common live (and will be improved on the future), it doesn't go well with hive tests.
This configuration change makes sure the pruner is not started during tests.

clients/reth: make sure `Pruner` doesn't start on tests

---

simulators/eth2/engine/Dockerfile
simulators/eth2/testnet/Dockerfile
simulators/eth2/withdrawals/Dockerfile

Fixes the golang docker image version to `golang:1.20-alpine` instead of `golang:1-alpine`, since the former now redirects to `golang:1.21-alpine` which breaks compilation.

simulators/eth2: Fix Docker golang version

---

clients/fluffy/Dockerfile
clients/trin-bridge/Dockerfile
clients/trin-bridge/trin_bridge.sh
clients/trin/Dockerfile
clients/trin/trin.sh
clients/ultralight/Dockerfile

portal-hive wasn't pulling the latest docker images I think this was why

clients/portal: update Dockerfiles to use baseimage/tag arg format

---

simulators/portal/beacon/Cargo.toml
simulators/portal/beacon/Dockerfile
simulators/portal/beacon/src/suites/rpc_compat.rs
simulators/portal/history/Cargo.toml
simulators/portal/history/Dockerfile
simulators/portal/history/src/suites/interop.rs
simulators/portal/history/src/suites/mesh.rs
simulators/portal/history/src/suites/rpc_compat.rs
simulators/portal/history/src/suites/trin_bridge.rs

We were using an older version which had a few bugs and is soon to be out dated with the spec.

simulators/portal: bump version of ethportal-api used

---

.circleci/continue_config.yml

Circleci smoke-test begun failing on march 4th as part of their brownout schedule of deprecated images.
This PR changes the machine to the default one as recommended in their post: https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177/9

circleci: Use default ubuntu machine

---

clients/fluffy/fluffy.sh

The cli option was added to individually enable networks in Portal for fluffy client.

clients/fluffy: use --networks cli option in fluffy client start script

---

simulators/ethereum/engine/helper/blobs.go
simulators/ethereum/engine/helper/tx.go

- Modify `BaseTransactionCreator` transaction creator to keep track of blobs instead of jumping 10,000+ unused blob IDs
- Fix `GetBlobListByIndex` since it was returning negative blob IDs
Down to only one failing test in some clients, this issue was causing a panic in the simulator.

simulators/ethereum/engine: TransactionCreator - Keep track of blobs

---

simulators/eth2/common/go.mod
simulators/eth2/common/go.sum
simulators/eth2/common/testnet/verification.go
simulators/eth2/dencun/go.mod
simulators/eth2/dencun/go.sum
simulators/eth2/dencun/suites/base/execution.go
simulators/eth2/dencun/suites/builder/config.go

- Builder tests now wait until all clients' builders have proposed at least one block with blobs, because some tests were erroneously failing during the verification phase.
- Bumped the Dencun fork epoch on the builder tests for clients that do _not_ require finalization, since nimbus was now taking one epoch before starting to request payloads from the builder, which resulted in a test fail.
- Use fix in #1030 to keep track of the blobs in the blob spammer used by all `eth2/dencun` tests, which resulted in the blob KZG cache not being used due to the blob IDs being too high

simulators/eth2/dencun: Fixes to builder tests

---

clients/nimbus-bn/Dockerfile
clients/nimbus-bn/Dockerfile.git
clients/nimbus-vc/Dockerfile
clients/nimbus-vc/Dockerfile.git

Currently nimbus images take too long to generate and they seem to randomly trigger a full rebuild even when the image was just recently built.
This PR changes the default Dockerfile to use the prebuilt ethpandaops images to speed up test execution while leaving the original file as the optional `Dockerfile.git` to be able to build from source and run hive tests.

clients/nimbus-bn,vc: Use ethpandaops prebuilt docker images

---

clients/nethermind/mkconfig.jq

Adds the `$HIVE_NODETYPE` env var to the nethermind start up script. Sets the appropriate flags if the node type is set to snap.
Passes the previously failed sync tests: https://hivetests.ethdevops.io/#suite=snap&client=nethermind

clients/nethermind: enable snap serving

---

simulators/eth2/common/go.mod
simulators/eth2/common/go.sum
simulators/eth2/dencun/go.mod
simulators/eth2/dencun/go.sum

Updates the blobber to the newest main which contains the following PRs:
https://github.com/marioevz/blobber/pull/39
https://github.com/marioevz/blobber/pull/41
Fixes test failures in lodestar.

simulators/eth2: Update blobber

---

clients/prysm-bn/Dockerfile
clients/prysm-vc/Dockerfile

Prysm's tag `latest-debug` seems to be outdated by a couple of months.
Tag `latest` seems to be up to date, so use that instead.

clients/prysm: use `latest` tag instead of `latest-debug`

---

simulators/eth2/common/go.mod
simulators/eth2/common/go.sum
simulators/eth2/dencun/go.mod
simulators/eth2/dencun/go.sum
simulators/eth2/dencun/suites/base/TESTS.md
simulators/eth2/dencun/suites/base/config.go
simulators/eth2/dencun/suites/base/execution.go
simulators/eth2/dencun/suites/builder/TESTS.md
simulators/eth2/dencun/suites/builder/config.go
simulators/eth2/dencun/suites/builder/execution.go
simulators/eth2/dencun/suites/builder/tests.go
simulators/eth2/dencun/suites/p2p/gossip/blobs/TESTS.md
simulators/eth2/dencun/suites/reorg/TESTS.md
simulators/eth2/dencun/suites/sync/TESTS.md

- The simulator now polls the mock builder for the requests it has received at `/eth/v1/builder/header/{slot}/{parent_hash}/{pubkey}` from each consensus client, and it immediately proceeds with the test once all clients have started requesting payloads, instead of having a hard-coded delay period for each client depending on whether the client waits for finality or not before requesting the builder for payloads.
- All tests now start from Deneb, and the injected builder faults start from the beginning, so the tests are much faster now (between 2-4 minutes if the client does not require for finalization to start requesting payloads from the builder).

simulators/eth2/dencun: Builder suite: Poll mock builder to wait for the CL to request payloads

---

clients/erigon/Dockerfile.git
clients/go-ethereum/Dockerfile.git
simulators/eth2/engine/Dockerfile
simulators/eth2/testnet/Dockerfile
simulators/eth2/withdrawals/Dockerfile
simulators/ethereum/engine/Dockerfile
simulators/ethereum/pyspec/Dockerfile

Our hive pyspec builds recently broke because the images were using 1.20, and `go.mod` files used go toolchains, which were released in 1.21. This just changes any images using 1.20, to using a 1.22 image.

all: use golang 1.22 in Dockerfiles

---

simulators/portal/beacon/Dockerfile
simulators/portal/history/Dockerfile
simulators/portal/state/Dockerfile

Adds a caching step in the docker build process for the `portal` simulators to allow for quicker rebuilding of simulator containers when working on `portal` hive tests locally.

simulators/portal: add docker caching step for building rust simulator dependencies

---

clients/ethereumjs/ethereumjs-local.sh
clients/ethereumjs/ethereumjs.sh

Fixes the docker build step for `ethereumjs` so hive can run again.
I've run this locally with both `dockerfile` and `dockerfile.local` and hive appears to run again.

Fix ethereumjs docker build steps

---

clients/ethereumjs/ethereumjs-local.sh
clients/ethereumjs/ethereumjs.sh

Resolves a few more scripting issues related to `ethereumjs`
Once this PR and [this ethjs PR](https://github.com/ethereumjs/ethereumjs-monorepo/pull/3414) are merged, EthereumJS can start running hive tests again

clients/ethereumjs: more script fixes

---

clients/trin-bridge/trin_bridge.sh

we no longer support the `--node-count` flag inside trin-bridge

clients/trin-bridge: update outdated bridge args

---

simulators/ethereum/sync/chain/headnewpayload.json

Reth does not support these fields as `null` when using newPayloadV2, and AFAIK it does not need to. We currently do not progress in this test because we report the request as malformed. This removes the `blobGasUsed` and `excessBlobGas` fields from the `ethereum/sync` test.

fix: remove blob fields from ethereum/sync newPayloadV2

---

clients/ethereumjs/Dockerfile
clients/ethereumjs/Dockerfile.local
clients/ethereumjs/ethereumjs-local.sh
clients/ethereumjs/ethereumjs.sh

- Updates the base image for the EthereumJS client Docker build to node 20
- Adds support for the `/blocks` parameter for loading multiple RLP encoded blocks (used primarily in the `ethereum/consensus` simulator

Update EthereumJS build to support RLP `/blocks`

---

clients/ethereumjs/mapper.jq

Pads storage keys to 32 bytes within the `genesis.json` for ethereumjs to resolve the following error:
```
[f8c2f37c] [05-30|18:42:16] ERROR Error starting client Storage key must be 32 bytes long
```
on client start up.
This appeared for us when trying to run our python based `consume rlp` simulator (using hive as the backend), which is essentially a port of the consensus simulator.
We could alternatively update this on our end, forcing storage keys to be 32 bytes long but this breaks some functionality for us as well as bloating the fixture content. We could also add the padding after processing the fixture content but as this is client specific it seems like adding this to the mapper within hive is the most reasonable approach.
This change will likely save us some error hunting when we …

clients/ethereumjs: pad genesis storage keys with mapper

---

clients/reth/reth.sh

AFAICT, pretty much all of the tests use the engine API now. `--debug.continuous` was an artifact of when the hive tests neither used the engine api, or some sort of mining / dev mode

clients/reth: remove --debug.continuous usage

---

clients/reth/reth.sh

This passes the `HIVE_CLIQUE_PERIOD` env variable to reth as its `--dev.block-time` param

clients/reth: pass HIVE_CLIQUE_PERIOD to reth script

---

clients/nimbus-el/nimbus.sh

Because of recent addition of AristoDB in Nimbus-eth1, `--prune-mode` no longer used. Now it is replaced by `--chaindb`

clients/nimbus-el: change command line option --prune-mode to --chaindb

---

simulators/ethereum/engine/suites/cancun/config.go
simulators/ethereum/engine/suites/cancun/steps.go
simulators/ethereum/engine/suites/cancun/tests.go

- Fixes the engine-cancun devp2p test: `Request Blob Pooled Transactions` for geth.
- After the following PR: https://github.com/ethereum/go-ethereum/pull/29026, to obtain a `NewPooledTransactionHashes` devp2p msg for blob txs, we must now peer first before sending blob txs.
- Adds an additional test where we send multiple blob txs instead of a single blob tx.

simulators/ethereum/engine/cancun: Maintain devp2p client peering

---

simulators/ethereum/engine/client/hive_rpc/hive_rpc.go
simulators/ethereum/engine/globals/globals.go

A simple PR to increase engine timeout values.
Some tests on the hive cancun public interface occasionally fail with the `context deadline exceeded` error. That is they pass most of the time but on occasion fail with this error.
1) For the `engine-cancun` tests we have the following [case](https://hivecancun.ethdevops.io/viewer.html?suiteid=1712709430-25ebe939b252698029586282b0af316e.json&suitename=engine-cancun&testid=216&file=%2Fresults%2Fnethermind%2Fclient-e4776ef8bda35d0b1b55b46f2b3a23c33bd2a749a1582662db3b787748adef18.log) that occurs waiting for an FCU response. The proposed solution is to increase the RPC timeout from 10 seconds to 20.
2) For the `pyspec` tests we have this [case](https://hivecancun.ethdevops.io/suite.html?suiteid=1712730801-2ce030e108054ff3b951b7db867a0fbf.json&su …

simulators/ethereum/engine: Increase engine timeouts

---

clients/fluffy/fluffy.sh

Add --disable-state-root-validation to Fluffy startup options to support Portal state hive tests.
I'm working on updating Fluffy in order to pass the portal state hive tests and this new parameter is now required when running the state tests against Fluffy.

clients/fluffy: Add --disable-state-root-validation to Fluffy startup options

---

simulators/ethereum/rpc-compat/testload.go

That error was silently ignored that's IMO the more important fix. But the tests for eth_simulateV1 are larger than bufio's default buffer size so it fails to load them.

simulators/ethereum/rpc-compat: bump buffer size for loading test

---

clients/shisui/shisui.sh

clients/shisui: enable `none` bootnodes for portal hive test

---

.circleci/config.yml
.circleci/continue_config.yml
.gitignore
hivesim-rs/Cargo.toml
hivesim-rs/src/lib.rs
hivesim-rs/src/macros.rs
hivesim-rs/src/simulation.rs
hivesim-rs/src/testapi.rs
hivesim-rs/src/testmatch.rs
hivesim-rs/src/types.rs
hivesim-rs/src/utils.rs

Since `hivesim-rs` is mature now I thought it makes sense to bring it over from `ethereum/portal-hive`
Even though we would need to update hivesim-rs first before we update the simulators that rely on it that shouldn't be that big of an issue as it is very stable now and I don't need to make constant changes to it. Also that is the same workflow currently done for `hivesim`
It is also nice for consistency sake that `hivesim-rs` lives with `hivesim`  in `ethereum/hive`

hivesim-rs: add hivesim-rs a rust implementation of hivesim

---

clients/reth/reth.sh

Closes https://github.com/ethereum/hive/issues/1073.
Enables discv5 on same port as discv4 for reth.

clients/reth: enable discv5

---

clients/reth/reth.sh

Reverts https://github.com/ethereum/hive/pull/1128 
Reth is running discv5 as an additional service, with its own port. https://github.com/ethereum/hive/issues/1073 needs another solution than using same port.

Revert pull/1128 

---

clients/ethereumjs/mapper.jq

It seems like genesis.json format has changed? The new mapper now allows accounts with empty storage (seems like before we required the storage field to be present)

clients/ethereumjs: fix for null storage in mapper

---

simulators/ethereum/engine/suites/withdrawals/tests.go

Lowers the withdrawal test timeout to a more sane value

simulators/ethereum/engine: lower withdrawals test timeout to 240s

---

clients/fluffy/fluffy.sh

The old flags are deprecated and will be removed in the future.

clients/fluffy: Update to the new subnetworks and network cli flags

---

simulators/portal/Dockerfile

updates our dockerfile for simulators/portal to pull from the main test file, there appears to be issues with our bridge handling epoch files.

simulators/portal: update test data file link

---

clients/ethereumjs/ethereumjs-local.sh
clients/ethereumjs/ethereumjs.sh

EthereumJS fails the "websocket" tests in `ethereum/rpc` because the startup script has the `--ws` flag set to `false`.
This sets the `--ws` option to true to enable the websocket server for these tests.

clients/ethereumjs: enable WS in startup script

---

clients/besu/Dockerfile.git
clients/besu/Dockerfile.local

Bump java distribution to 21: https://github.com/hyperledger/besu/issues/6722

clients/besu: Bump java distribution

---

simulators/ethereum/pyspec/Dockerfile

ref https://github.com/ethereum/execution-spec-tests/pull/687

simulators/ethereum/pyspec: fix fixture directory name on `Dockerfile`

---

internal/libdocker/docker.go

While trying to run the hive tests locally I'm using the --docker.endpoint parameter. This was previously working for me but now is broken.
In the code it appears that the parameters are being passed in the wrong order in the call to docker.NewVersionedClient.
It appears that this issue was introduced in this PR: https://github.com/ethereum/hive/pull/1125/files

internal/libdocker: fix param order for docker.NewVersionedClient

---

.circleci/continue_config.yml
simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/Dockerfile
simulators/portal/src/suites/beacon/interop.rs
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/state/interop.rs

Updates ethportal api so state tests use the latest version of ethportal-api which supports the latest state spec
@web3-developer

simulators/portal: update ethportal-api version

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/beacon/interop.rs
simulators/portal/src/suites/beacon/mesh.rs
simulators/portal/src/suites/beacon/rpc_compat.rs
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/history/mesh.rs
simulators/portal/src/suites/history/rpc_compat.rs
simulators/portal/src/suites/history/trin_bridge.rs
simulators/portal/src/suites/state/interop.rs
simulators/portal/src/suites/state/rpc_compat.rs

Update Portal simulators to use updated version of hivesim (with generic test data type, see #1150).
I run the tests locally and I didn't observe any unexpected behavior or tests failing

simulators/portal: update portal simulators to newest version of hivesim 

---

simulators/portal/src/suites/beacon/constants.rs
simulators/portal/src/suites/beacon/interop.rs
simulators/portal/src/suites/beacon/mesh.rs
simulators/portal/src/suites/beacon/rpc_compat.rs
simulators/portal/src/suites/environment.rs
simulators/portal/src/suites/mod.rs
simulators/portal/src/suites/state/constants.rs
simulators/portal/src/suites/state/interop.rs
simulators/portal/src/suites/state/rpc_compat.rs

The state network should verify that content is anchored to the canonical blockchain. For that, in needs access to the block header, which we have to seed at the start of the test.
Now that some tests require more than one portal network running, I refactored how that is configured.

simulators/portal: store block header before gossip and offer state requests

---

internal/libhive/run.go

To reproduce the issue, set this clients definition:
```yaml
- client: go-ethereum
nametag: multicall-git
dockerfile: git
build_args:
github: s1na/go-ethereum
tag: multicall
- client: nethermind
nametag: multicall-git
dockerfile: git
build_args:
github: NethermindEth/nethermind
tag: feature/eth_simulate_fix
```
The branch feature/eth_simulate_fix has been removed from the nethermind repo. This causes the container build to fail:
```
Cloning: NethermindEth/nethermind - feature/eth_simulate_fix
Cloning into 'nethermind'...
fatal: Remote branch feature/eth_simulate_fix not found in upstream origin
EROR[08-20|11:49:12] image build failed                       image=hive/clients/nethermind_multicall-git:latest err="The command '/bin/sh -c echo \"Cloning: $github - $tag\" &&     git clone -b …
```

internal/libhive: skip unsuccessful build of client

---

clients/erigon/erigon.sh

https://github.com/erigontech/erigon/pull/11300 introduced a performance optimization that's fine with the actual CL workflow but that breaks Hive tests

clients/erigon: disable incompatible performance optimization

---

clients/trin-bridge/trin_bridge.sh
clients/trin/trin.sh

@kdeme ping for review
This PR removes most of the spammy logs which don't say anything about what is happening, well maintaining the ones which should be useful

clients/trin*: update log levels to be cleaner + informative

---

simulators/ethereum/engine/suites/engine/invalid_payload.go

Fixes the ForkchoiceUpdated expected response to also allow `INVALID` if the test expects that some of the clients can detect an invalid payload even on `SYNCING`.
Fixes a failing test for Reth.

simulators/ethereum/engine: Fix SYNCING FCU expectation

---

clients/besu/mapper.jq
clients/erigon/mapper.jq
clients/ethereumjs/mapper.jq
clients/go-ethereum/mapper.jq
clients/nethermind/mapper.jq
clients/nimbus-el/mapper.jq
clients/reth/mapper.jq

Adds `pragueTime` to all EL clients' mappers.

clients/besu,erigon,ethereumjs,go-ethereum,nethermind,reth,nimbus-el: Add `pragueTime`

---

clients/erigon/Dockerfile

We're moving from `thorax` to `erigontech` on DockerHub. Tag `latest` there points to the latest release instead of the latest commit to branch `main`.

clients/erigon: update dockerhub

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/history/trin_bridge.rs
simulators/portal/src/suites/mod.rs
simulators/portal/src/suites/utils.rs

We moved these utils to another crate at the time to reduce code duplication, but with the refactors I did a while ago that workaround is no longer needed.

simulators/portal: move test utils back to Portal simulator

---

clients/trin-bridge/trin_bridge.sh

Trin bridge no longer needs the cli flag specifying the client type.

clients/trin-bridge: remove unnecessary trin bridge cli arg

---

clients/fluffy/fluffy.sh

Fluffy's default RPC APIs are now eth and portal but the Discv5 API is used on the portal hive tests so this is needed to enable it.

Add --rpc-api flag to Fluffy startup script

---

clients/erigon/Dockerfile.git

The `devel` branch has been deprecated, the `main` branch houses the latest and greatest now for Erigon.

clients/erigon: update erigon tag

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/beacon/interop.rs
simulators/portal/src/suites/beacon/mesh.rs
simulators/portal/src/suites/beacon/rpc_compat.rs
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/history/mesh.rs
simulators/portal/src/suites/history/rpc_compat.rs
simulators/portal/src/suites/history/trin_bridge.rs
simulators/portal/src/suites/state/interop.rs
simulators/portal/src/suites/state/rpc_compat.rs

Our old ContentInfo type was exposing implementation internals which was bad

simulators/portal: update ethportal-api for cleaner return types for ContentInfo

---

hive.go
internal/fakes/builder.go
internal/libdocker/builder.go
internal/libhive/dockerface.go
internal/libhive/run.go
internal/libhive/run_test.go
internal/libhive/testmanager.go

Adds `--sim.buildarg` as a parameter to add build arguments to the simulator Dockerfile.

hive: add --sim.buildarg flag

---

simulators/ethereum/eest/consume-engine/Dockerfile
simulators/ethereum/eest/consume-rlp/Dockerfile

Updates the consume simulator dockerfiles to use input build args. This will allow us to pass different release fixtures dynamically to both `consume rlp` and `consume engine`.
The default remains as `latest-stable-release`, as these are the fixtures that validate client mainnet releases.
The PR requires that #1179 is merged first, as it utilizes the `--sim.buildarg` flag that the latter adds.

simulators/eth/eest: use `--sim.buildarg` for consume

---

clients/nethermind/Dockerfile.git

`dotnet/sdk:9.0-jammy` isn't a valid tag of a dotnet dokcer image, ref: https://github.com/dotnet/dotnet-docker/blob/main/README.sdk.md#full-tag-listing

Nethermind jammy->noble dotnet9

---

simulators/ethereum/eest/consume-engine/Dockerfile
simulators/ethereum/eest/consume-rlp/Dockerfile

Adds another build argument to the EEST simulators' Docker files that can be used to configure which EEST branch is used to run the fixtures.

simulators/ethereum/eest: Add `branch` buildarg

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/state/interop.rs

updates tests to match spec https://github.com/ethereum/portal-network-specs/pull/346
@bhartnett for a quick look

simulators/portal: update gossip to put content tests

---

internal/libdocker/builder.go

the err has been checked in line 115 and is a nil value in line 119

internal/libdocker: return context error correctly in archiveFS

---

simulators/ethereum/engine/README.md

This pull request fixes a typo in the `README.md` file. The word "everytime" has been corrected to "every time."
- Corrected the spelling of "everytime" to "every time" in the text explaining the verification process for the Eth RPC after reorgs.
- `simulators/ethereum/engine/README.md`
Correcting the typo ensures proper grammar and improves the clarity of the documentation.
N/A
N/A

simulators/ethereum/engine: fix typo in README.md

---

simulators/ethereum/engine/client/node/node.go
simulators/ethereum/engine/config/genesis.go
simulators/ethereum/engine/devp2p/conn.go
simulators/ethereum/engine/globals/globals.go
simulators/ethereum/engine/main.go
simulators/ethereum/engine/suites/auth/tests.go

Contains the following fixes:
- Fixed an incorrect handling of the `Process` returned value in the geth-node module.
- The genesis configure method now does actually set the TTD because the geth-node module fails to start if the value is nil.
- Remove `HIVE_CLIQUE_PERIOD`, `HIVE_CLIQUE_PRIVATEKEY`, and `HIVE_MINER` are removed.
- Remove Total Difficulty check in the devp2p library because it resulted in nil pointer exception.
- Fix TTD in the auth test suite.

simulators/ethereum/engine: TTD related fixes

---

clients/go-ethereum/mapper.jq

Most of the requests-related failing tests in https://hive.pectra-devnet-5.ethpandaops.io (for geth) are because the deposit contract address is not properly configured. I have for now hardcoded it in the starter script. But probably best to set it as an environment parameter from the simulator?

clients/go-ethereum: hardcode deposit contract address

---

cmd/hiveview/assets/index.html
cmd/hiveview/assets/lib/routes.js
cmd/hiveview/assets/suite.html
cmd/hiveview/assets/viewer.html

This will allow hiveview to also work with relative paths.
Example: `http://youdomain.com/relative-path/`
This is useful in my case where I'm using a single S3 bucket to publish multiple hiveview UIs across different subpaths.

cmd/hiveview: enable asset loading with relative paths

---

clients/shisui/Dockerfile

client shisui has moved to [zen-eth](https://github.com/zen-eth/shisui) organization, so the docker image should be update

client/shisui: change docker image repo

---

hive.go

I already had a couple of flaky runs in CI runners where building an image failed. I noticed that there was the `docker.output` flag, that would show the problem. But it would also enable log output for any container that hive runs. To avoid adding too much unnecessary logging to the test runs, I've added a flag that just enables the docker outputs for any image that is built.
Example failure on a CI job:
```
Jan 17 16:52:43.498 INF building image image=hive/hiveproxy nocache=false pull=false
Jan 17 16:53:00.502 ERR image build failed image=hive/hiveproxy err="The command '/bin/sh -c go mod download' returned a non-zero code: 1"
The command '/bin/sh -c go mod download' returned a non-zero code: 1
```

hive: add flag to enable just docker build outputs to stderr

---

internal/libdocker/builder.go

This pull request addresses a typo in the `builder.go` file, correcting **"specifes"** to **"specifies**. This change improves the readability and accuracy of the code comments.
- Replaced **"specifes"** with **"specifies"** in `builder.go`.
``

internal/libdocker: fix typo in comment

---

clients/trin/Dockerfile
clients/trin/Dockerfile.git
clients/trin/trin_version.sh

We want to test experimental branches of Portal clients, here is a PR so we can use a clients file for trin and pull a git branch

clients/trin: add Dockerfile support to build Trin from git

---

clients/erigon/mapper.jq

Without this deposit and deposit request related tests may fail as erigon doesn't use default for this value

clients/erigon: Add deposit contract to mapper jq

---

clients/fluffy/Dockerfile.git

Here is a PR making is so we can compile feature branches or commits for fluffy, this is useful for us testing if ping extensions work before I deploy it

clients/fluffy: add Dockerfile support to build Fluffy from git

---

clients/trin-bridge/Dockerfile
clients/trin-bridge/Dockerfile.git
clients/trin-bridge/trin_bridge_version.sh

We need to add Dockerfile.git for testing the Portal clients with Ping extensions 
@kdeme ping for review

clients/trin-bridge: add Dockerfile support to build Trin Bridge from git

---

clients/ultralight/Dockerfile.git

In ultralight's new ping extension branch they require the .git folder be accessible in the base directly in this case it is the root direclty.
@acolytec3 for review

clients/ultralight: move .git to root directory

---

clients/go-ethereum/mapper.jq

I believe this is the correct default value because EEST tests will not provide a value for TOTALTERMINALDIFFICULTY when testing HFs prior to the merge and in that case we shouldn't assume to be post-PoW.

clients/go-ethereum: fix default TTD

---

clients/go-ethereum/mapper.jq

As per https://github.com/ethereum/go-ethereum/pull/31002 every configured HF needs to have a blob schedule entry. I don't see any reason to make the cancun schedule configurable but happy to change if people disagree.

clients/go-ethereum: add cancun blob schedule

---

clients/reth/reth.sh

```
eest/consume-rlp : tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py::test_block_hashes_history[fork_Prague-blockchain_test-full_history_plus_one_check_blockhash_first]-reth
```
The above test would call the import command block by block. For a total of 8192 blocks. This would result in a timeout, since staged sync (used on `reth import`) is not suited for single blocks.
Combines all individual blocks into one file, before importing them into reth

clients/reth: combine remaining blocks before import 

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml

In one of our tests we use `generate_random_remote_enr()` which could generate any any Ipv4 address in the range, now it won't generate Multicast IP addresses

simulators/portal: bump ethportal-api to remove multicast ip generation

---

clients/reth/reth.sh

Previous PR https://github.com/ethereum/hive/pull/1230 fixed some, but broke other tests setup. This should cover both cases.
> First import as many blocks as possible, and only then import the last one.
> This is important because usually tests expecting a failure will assert that the last valid inserted block is at `last - 1`. If we attempted to import all of them the pipeline would unwind the whole range.
run: https://github.com/paradigmxyz/reth/actions/runs/13084266651

clients/reth: combine all blocks except the last before import 

---

clients/trin/trin.sh

Trin recently made it so the default radius is 5 percent, but the tests are hive are designed for 100% radius

clients/trin: set max default radius to 100%

---

clients/ultralight/ultralight.sh

Adds new startup parameters to Ultralight for `HIVE_TRUSTED_BLOCK_ROOT` and `HIVE_BOOTNODES` to support the new `beacon-sync` test suite.

clients/ultralight: update ultralight startup parameters

---

simulators/portal/src/suites/beacon/bridge/service.rs
simulators/portal/src/suites/beacon/sync.rs

**The issue**:
The `portal/beacon-sync` test suite currently pulls test data from a live beacon node in order to test syncing the Portal beacon light clients. 
The bridge client that retrieves the finalized and optimistic updates continues to pull new updates from the beacon client as long as the test is running.
This can be an issue in the `optimistic update` test where a new optimistic update is produced every slot.  
Only one optimistic update is pushed into the network and the simulator then retrieves a new update from the bridge to compare to when validating the test results.  
**The solution**
Add a parameter to the `start` method in the `BridgeService` that tells the bridge whether to continue to retrive new updates from the Beacon Node provider or not.  In the the `optimistic …

simulators/portal: fix race condition in `beacon-sync` suite

---

clients/shisui/shisui.sh

1. change env `HIVE_BOOTNODE` to `HIVE_BOOTNODES`
2. add support for `HIVE_TRUSTED_BLOCK_ROOT`

clients/shisui: add support for env HIVE_TRUSTED_BLOCK_ROOT

---

cmd/hiveview/listing.go
hivesim/data.go

This is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

cmd/hiveview, hivesim: using slices.Contains to simplify the code

---

clients/besu/Dockerfile.git
clients/besu/Dockerfile.local

Besu's docker builds (from git) started failing after they updated the version of `gradlew` used. Looks like the fix is simply to require the JDK instead of the JRE (runtime environment). No idea, why this worked before. The fix was taken from this comment:
- https://github.com/hyperledger/besu/issues/8310#issuecomment-2662275519
Confirmed build works locally with `Dockerfile.git`.

clients/besu: use JDK instead of JRE for docker builds

---

clients/erigon/Dockerfile

Erigon's image dockerfile fails to build as its now Debian based. This PR updates the dependencies to install correctly.

clients/erigon: fix build image dockerfile

---

clients/erigon/Dockerfile.git

Build started failing on our hive CI

clients/erigon: Update golang builder version in Dockerfile

---

clients/nethermind/mapper.jq

`depositContractAddress` is missing in the `clients/nethermind/mapper.jq` config file; it is causing the nethermind container to terminate unexpectedly

add deposit contract address in the nethermind config

---

clients/besu/mapper.jq
clients/erigon/mapper.jq
clients/ethereumjs/mapper.jq
clients/go-ethereum/mapper.jq
clients/nethermind/mapper.jq
clients/reth/mapper.jq

Adds Osaka to client `mapper.jq` files. Required for running EOF tests correctly within `consume rlp/engine`.

clients: add osaka to client mappers

---

clients/shisui/shisui.sh

@KolbyML 
the `--disable-init-check` flag put the wrong place, cause the fail in hive test

clients/shisui: hot fix for the wrong flags

---

clients/go-ethereum/geth.sh

Fixes this: https://hive.ethpandaops.io/pectra/suite.html?suiteid=1743168974-9aafccfb8a9d722e08d1065273e7ad82.json#test-1
We recently removed the --nocompaction flag, see https://github.com/ethereum/go-ethereum/commit/714fa4f2e69a53ad714d6a0a259ab1c8b2032845

clients/go-ethereum: update geth.sh

---

clients/nimbus-el/Dockerfile

Now uses a docker image from the registry. The git build approach is used in Dockerfile.git

clients/nimbus-el: add base docker image

---

simulators/ethereum/eest/consume-engine/Dockerfile
simulators/ethereum/eest/consume-rlp/Dockerfile

Updates the consume rlp and engine dockerfiles.
- Used the `python:3.10-slim` as the base docker image installing additional packages including uv. 
- Now uses the `ghcr.io/astral-sh/uv:python3.10-bookworm-slim` as the base docker image. No longer requires wget, tar, and uv installs.
- Renames the `INPUT` env var to `FIXTURES`.
- Combines some `RUN` commands to make the Dockerfiles more compact overall.

simulators/ethereum/eest: update consume dockerfiles

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/state/interop.rs

The json-rpc https://github.com/ethereum/portal-network-specs/pull/370 was modified

simulators/portal: bump ethportal-api for offer json-rpc changes

---

simulators/portal/src/suites/beacon/rpc_compat.rs
simulators/portal/src/suites/history/rpc_compat.rs
simulators/portal/src/suites/state/rpc_compat.rs

A PR was made on our specs which was caused by `portal_*GetContent` not being fully tested on Hive causing different results between clients.
Fluffy didn't check the local database
Trin did
`portal_*GetContent` should always check locally fix as it is the cheapest
fixes https://github.com/ethereum/portal-network-specs/pull/344

simulators/portal: add test for if GetContent checks locally

---

clients/ultralight/Dockerfile
clients/ultralight/Dockerfile.git

Currently Ultralight exposes no information about what version is being ran on hive, it looks like an old version is being ran on our main instance
^ this is what it will look like now, before it showed "latest"

clients/ultralight: expose clients commit hash as version.txt for hiveview

---

clients/trin/trin.sh
simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/state/interop.rs
simulators/portal/src/suites/state/rpc_compat.rs

With recent  change in trin (https://github.com/ethereum/trin/pull/1775), we need to enable Beacon subnetwork in all tests and add it as a default flag for trin client.
I also updated ethportal-api library version.

feat: enable beacon subnetwork for trin client and in portal simulators

---

simulators/portal/Dockerfile
simulators/portal/src/suites/beacon/constants.rs
simulators/portal/src/suites/history/constants.rs
simulators/portal/src/suites/state/constants.rs

We are updating our test data format so we don't just read a gigantic yaml file. We are starting out with History because that is the priority right now, but we will expand over time

simulators/portal: update history tests to use new test data format

---

simulators/portal/Cargo.lock
simulators/portal/Cargo.toml
simulators/portal/src/suites/beacon/bridge/provider.rs
simulators/portal/src/suites/history/constants.rs
simulators/portal/src/suites/history/interop.rs
simulators/portal/src/suites/history/mesh.rs

To validate post capella content, clients require access to HistoricalSummaries

simulators/portal: initial clients during history tests with HistoricalSummaries

---

simulators/portal/src/suites/utils.rs

I added test data for testing if we handle fork boundaries properly and from this I found we have an off by one error when calculating the flair for the test title

simulators/portal: fix off by 1 error in flair calculation

---

simulators/ethereum/eest/execute-blobs/Dockerfile

Adds new simulator `execute-blobs` which uses the EEST `execute` command to run blob tests:
- Send blob transactions with cell proofs to the client.
- Use `engine_getBlobsV2` to get proofs back from the client
- Verify proofs
At the moment contains only three tests and relies on branch [`devnets/osaka/0`](https://github.com/ethereum/execution-spec-tests/tree/devnets/osaka/0), but more tests will be added soon.

simulators/ethereum/eest: New simulator `execute-blobs`

---

clients/ethrex/ethrex.sh

In ethrex's entrypoint script it exited when the environment variable HIVE_TOTAL_DIFFICULTY was set, as the client doesn't support pre merge block. Some tests use it even if they're post merge, so I have changed the entrypoint script to just emit a warning.

clients/ethrex: fixed ethrex tests failing due to premature exit

---

clients/nimbus-el/mapper.jq

Adds support for testing osaka fork in nimbus execution client

clients/nimbus-el: add osaka support

---

clients/erigon/Dockerfile

This reverts commit e6a0348b4067683fdd15b5ce02e106ea07689d6e.
Reason: The change in baseimage to debian was reverted for the default dockerfile

clients/erigon: Revert "clients/erigon: fix build image dockerfile (#1251)"

---

hive.go
internal/fakes/container.go
internal/libdocker/container.go
internal/libdocker/proxy.go
internal/libhive/api.go
internal/libhive/cleanup.go
internal/libhive/cleanup_test.go
internal/libhive/data.go
internal/libhive/data_test.go
internal/libhive/dockerface.go
internal/libhive/run.go
internal/libhive/testmanager.go

This PR implements container labeling and naming system for Hive, enabling easier cleanup, monitoring, and management of containers. The system provides persistent metadata that survives Hive crashes and allows for background cleanup operations.
- **Standardized label schema**: All containers get consistent labels with `hive.` prefix
- **Rich metadata**: Labels include instance ID, version, container type, test context, and timestamps
- **Unique instance tracking**: Each Hive run gets a unique instance ID for identification
- **Context-aware labeling**: Client, simulator, and proxy containers get type-specific labels
- **Hive-prefixed names**: All containers now have descriptive names starting with `hive-`
- **Context inclusion**: Names include container type, client/simulator names, and …

feat: add names and labels to containers

---

clients/erigon/Dockerfile.git
clients/go-ethereum/Dockerfile.git
clients/shisui/Dockerfile.git
hiveproxy/Dockerfile
simulators/devp2p/Dockerfile
simulators/eth2/dencun/Dockerfile
simulators/eth2/engine/Dockerfile
simulators/eth2/testnet/Dockerfile
simulators/eth2/withdrawals/Dockerfile
simulators/ethereum/consensus/Dockerfile
simulators/ethereum/engine/Dockerfile
simulators/ethereum/graphql/Dockerfile
simulators/ethereum/rpc-compat/Dockerfile
simulators/ethereum/rpc/Dockerfile
simulators/ethereum/sync/Dockerfile
simulators/smoke/clique/Dockerfile
simulators/smoke/genesis/Dockerfile
simulators/smoke/network/Dockerfile

Sometimes we have some CI runs that get blocked by the default proxy. This changed makes it possible to define our own proxy when fetching go packages.

feat: add optional GOPROXY build arg and use it as an env var

---

clients/nethermind/mapper.jq

Adds EIP-7907 to the nethermind mapper to activate for fusaka devnet 2.

chore(clients): update nethermind mapper for fusaka devnet 2

---

clients/reth/Dockerfile
clients/reth/Dockerfile.git
clients/reth/Dockerfile.local

Hiveview reports reth's version without a commit hash: `reth Version: 1.3.8`. 
This PR adds the build's commit hash: `1.3.8+52c3e3cc`.
Try it out with the full output of `reth --version`:
```
echo "reth Version: 1.3.8
Commit SHA: df6d5dd1dd23da180ecd2e15585b3bebc3b5c656
Build Timestamp: 2025-04-14T08:43:20.271808115Z
Build Features: jemalloc
Build Profile: release" | head -2 | awk 'NR==1 {gsub("reth Version: ", ""); version=$0} NR==2 {gsub("Commit SHA: ", ""); sha=substr($0, 1, 8)} END {print version"+"sha}'
```
It's more brittle, but I don't think unexpected output would prevent the image getting built. 
These checks should be outsourced to a helper library that we can independently unit test.

clients/reth: improve version parsing in dockerfiles

---

clients/erigon/Dockerfile

With https://github.com/erigontech/erigon/pull/15757 erigon is switching to Debian based docker image.
Please, approve it in order to keep your workflow running fine.
This change redo https://github.com/ethereum/hive/pull/1251.

clients/erigon: Update Dockerfile

---

simulators/ethereum/engine/client/hive_rpc/hive_rpc.go
simulators/ethereum/engine/helper/helper.go

Forces RPC log trimming to only take affect when `--sim.loglevel <= 3`. I.e to get the full log we run with:
`--sim.loglevel 4` or `--sim.loglevel 5`. 
This PR can be regarded as an extension to following: https://github.com/ethereum/hive/pull/928
cc'ing @flcl42

simulators/ethereum/engine: Trim rpc logs only at low log levels

---

simulators/ethereum/eest/consume-engine/Dockerfile
simulators/ethereum/eest/consume-rlp/Dockerfile
simulators/ethereum/eest/execute-blobs/Dockerfile

Bump base image used by EEST simulators from Python 3.10 to 3.12. Python 3.10 support is planned for removal, cf https://github.com/ethereum/execution-spec-tests/pull/1808.

simulators/ethereum/eest: bump base image to python 3.12

---

simulators/ethereum/eest/consume-engine/Dockerfile
simulators/ethereum/eest/consume-rlp/Dockerfile

Installs `execution-spec-tests` via `uv pip install git+https://github.com/ethereum/execution-spec-tests.git` instead of cloning the repository into the docker container.
When EEST is published to PyPi we can skip installing git completely too.

simulators/ethereum/eest: Skip git clone

---

clients/nethermind/Dockerfile
clients/nethermind/Dockerfile.git
clients/nethermind/Dockerfile.local
clients/nethermind/enode.sh
clients/nethermind/mkconfig.jq
clients/nethermind/nethermind.sh

Using logs is too fragile. It's not ideal to get the enode from the logs in the first place - and, as in my case, if the log level is set lower it's never able to parse the `enode` from the logs as it never shows up. All other clients use the `admin_nodeInfo` request for this purpose and we should do so for Nethermind as well.
This also turns on `admin` module as this was necessary for this change.

refactor(nethermind): Refactor enode parsing to not use logs

---

clients/besu/mapper.jq
clients/erigon/mapper.jq
clients/go-ethereum/mapper.jq
clients/nethermind/mapper.jq
clients/nimbus-el/mapper.jq
clients/reth/mapper.jq

Integrates the BPO1 ruleset addition added in EEST: https://github.com/ethereum/execution-spec-tests/pull/2035/
Required for testing BPO forks with consume rlp/engine. BPO2/3/4/5 can be added in the future.

clients: add bpo1 to client mappers

---

clients/erigon/erigon.sh

Disable Caplin in Erigon. Allows RPC calls from simulators. Prevents the following error from EEST simulators:
```bash
ethereum_test_rpc.types.JSONRPCError: JSONRPCError(code=-38005, message=caplin is enabled)
```

clients(erigon): disable caplin in hive

---

clients/ethrex/Dockerfile

Ethrex's Docker image [is being refactored](https://github.com/lambdaclass/ethrex/pull/3826) and will have a minimalist distroless image as base, instead of the current Ubuntu. This change breaks Hive tests running as the new image doesn't have some tools and commands.
In this PR, the binary from the official image is copied into an Ubuntu image to keep compatibility

clients/ethrex: update Dockerfile

---

simulators/ethereum/rpc-compat/main.go
simulators/ethereum/rpc-compat/testload_speconly_test.go

This PR looks for the `speconly` flag that comes in in the comments from execution-api tests and only checks the structure of the JSON, not the values. If we decide to pull it in, I'll mark at least the estimateGas tests and maybe others(?) as speconly.
Based on the convo [here](https://discord.com/channels/595666850260713488/804019759934078987/1420084584586022972). 
cc @fjl and @lightclient

simulators/ethereum/rpc-compat: special handling for speconly tests
