ethereum/hive

- README.md
- clients/parity:beta/chain.json
- clients/parity:beta/parity.sh
- clients/parity:master/chain.json
- clients/parity:master/parity.sh
- clients/parity:stable/chain.json
- clients/parity:stable/parity.sh
Fixes https://github.com/ethcore/parity/issues/2007
> Add built-ins to parity chain spec

- clients/parity:beta/Dockerfile
- clients/parity:master/Dockerfile
- clients/parity:stable/Dockerfile
There were some strange switches there. See https://github.com/karalabe/hive/issues/18
> Fix parity client

- clients/parity:beta/Dockerfile
- clients/parity:master/Dockerfile
- clients/parity:stable/Dockerfile
Parity requires some [new dependencies](https://github.com/ethcore/parity/commit/7454212b28706508550dd3e9cdd79e254704a02f).
> update parity required deps and rust uninstall script

- clients/cpp-ethereum:develop/Dockerfile
- clients/go-ethereum:master/Dockerfile
- clients/go-ethereum:stable/Dockerfile
- clients/parity:beta/parity.sh
- clients/parity:master/Dockerfile
- clients/parity:master/parity.sh
- clients/parity:stable/Dockerfile
- simulators/ethereum/consensus/Dockerfile
- simulators/ethereum/consensus/hivemodel.py
- simulators/ethereum/consensus/simulator.py
- simulators/ethereum/consensus/testmodel.py
> Fixed some Parity issues, and CPP-ethereum integration

- clients/go-ethereum:local/geth.sh
- clients/go-ethereum:master/geth.sh
- clients/go-ethereum:stable/Dockerfile
- clients/go-ethereum:stable/geth.sh
- internal/ethash/ethash.go
- simulators/ethereum/consensus/hivemodel.py
- simulators/ethereum/consensus/testmodel.py
* added retries on failing instance-startup,  
* added speedier block import in geth, 
* added testcase time measurements
> Faster geth imports, measure times, Ethash log fix

- containers.go
- simulator.go
- simulators/ethereum/consensus/hivemodel.py
We were leaking up to two goroutines for every node started, and when
using loglevel>5, one of them would leave open FDs behind as well,
which would eventually cause the hive node to not be able to start
any more nodes due to having too many open files.
Also remove some trailing whitespace and simplify a couple things.
> Fix a couple goroutine leaks

- clients/parity:beta/parity.sh
- clients/parity:master/parity.sh
- clients/parity:stable/parity.sh
> Fixed error in parity.sh

- simulators/ethereum/consensus/hivemodel.py
- simulators/ethereum/consensus/testmodel.py
For more info: https://github.com/karalabe/hive/pull/41/files#r112965201
> Do not prefix addresses with 0x for the preState of consensus tests

- AUTHORS
- clients/pyethereum:develop/Dockerfile
- clients/pyethereum:develop/config.yaml
- clients/pyethereum:develop/importblock.py
- clients/pyethereum:develop/pyethapp.sh
- validators/smoke/genesis-chain-blocks/test.sh
- validators/smoke/genesis-chain/test.sh
- validators/smoke/genesis-only/test.sh
In two separate commits since I wanted to keep the original one (from
@cdetrio) intact, but happy to squash them if preferred.
> Add the pyethereum:develop client

- clients/cpp-ethereum:develop/Dockerfile
> Fix bash error in cpp-ethereum

- clients/pyethereum:develop/Dockerfile
- clients/pyethereum:develop/importblock.py
It broke with the massive changes that were merged recently onto
pyethapp/pyethereum.
> Fix pyethereum:develop client

- simulators/ethereum/consensus/simulator.py
- simulators/ethereum/consensus/testmodel.py
This PR contains the new definitions used in ethereum/tests. This does not contain any changes to the client bashfiles (and I'm not sure any change is needed)
> Add new definitions of rulesets

- clients/cpp-ethereum:develop/eth.sh
- clients/parity:master/parity.sh
This is running on hive now, I'll merge if it it seems to work. Stats, pre-patch:
`6973 : 13013  / 19986`
> Configure cpp and parity for metro

- simulators/ethereum/consensus/hivemodel.py
- simulators/ethereum/consensus/simulator.py
- simulators/ethereum/consensus/testmodel.py
Overrides https://github.com/karalabe/hive/pull/70  . I'll try this out on the hive server, and merge if it looks good.
> Disable constantinople

- clients/cpp-ethereum:develop/config.json
- clients/cpp-ethereum:develop/eth.sh
In combination with https://github.com/ethereum/cpp-ethereum/pull/4488, should fix many Byzantium failures on hivetests.ethstats.net.
> cpp config for byzantium

- clients/cpp-ethereum:develop/eth.sh
What https://github.com/karalabe/hive/pull/73 was supposed to be.  requires https://github.com/ethereum/cpp-ethereum/pull/4488
> actual fix for cpp Byzantium

- clients/cpp-ethereum:develop/eth.sh
- clients/parity:master/Dockerfile
- clients/parity:master/chain.json
- clients/parity:master/parity.sh
Trying this out now, will merge if it works
> Use parity metro branch

- clients/go-ethereum:local/geth.sh
- clients/go-ethereum:master/geth.sh
- clients/go-ethereum:metro/geth.sh
- clients/go-ethereum:stable/geth.sh
Update `metropolisBlock` to `byzantiumBlock`, see https://github.com/ethereum/go-ethereum/pull/15146
> geth: s/metropolisBlock/byzantiumBlock

- clients/ethereumj:develop/Dockerfile
- clients/ethereumj:develop/harmony.sh
- clients/ethereumj:master/Dockerfile
- clients/ethereumj:master/harmony.sh
- simulators/dao-hard-fork/network-split/Dockerfile
- simulators/dao-hard-fork/synchronisation/Dockerfile
Let's add EthereumJ, Ethereum Java implementation. It passes smoke, all validations, but fails on most simulations. As I understand, minimal requirements are to pass smoke so we could jump in. 
Also I've updated go-ethereum master and develop Dockerfiles to include required libs during the build as it fails for me (and I see you've included them in metro setup too).
We will continue to work with failed simulations tests later, need to switch to other tasks currently. If it requires another updates in Hive (hope, not) I'll submit another PR later.
> Adding EthereumJ client to Hive

- clients/ethereumj:local/Dockerfile
- clients/ethereumj:local/build.sh
- clients/ethereumj:local/harmony.sh
- clients/ethereumj:local/logback.xml
- clients/ethereumj:local/version.json
One more thing from us. Added local configuration for EthereumJ (Java Ethereum implementation) to use Hive in local environment and on CI. 
Also, could you let me know how to add EthereumJ tests results on CIrcleCI to this statistics: http://hivetests.ethstats.net/
Thank you.
> EthereumJ local configuration

- clients/cpp-ethereum:develop/eth.sh
Fix renamed flags due to https://github.com/ethereum/cpp-ethereum/pull/4635
> Fix renaming of cpp flags

- clients/ethereumj:develop/Dockerfile
- clients/ethereumj:develop/harmony.sh
- clients/ethereumj:master/Dockerfile
- clients/ethereumj:master/harmony.sh
Hi again. I think it's the fastest way we could do, so it could run just from the start of container.
> Speedup develop and master test runs for EthereumJ 

- clients/go-ethereum:local/geth.sh
- clients/go-ethereum:master/geth.sh
- clients/go-ethereum:stable/geth.sh
As per https://github.com/ethereum/go-ethereum/pull/16098
> fix --gcmode=archive during block import

- clients/go-ethereum:local/geth.sh
- clients/go-ethereum:master/geth.sh
- clients/go-ethereum:stable/geth.sh
- simulators/ethereum/consensus/testmodel.py
> define constantinople rules

- internal/ethash/Dockerfile
Fixes so it doesn't require root user
> Fix https://github.com/karalabe/hive/issues/103

- clients/parity:master/Dockerfile
Parity stopped working sometime after https://github.com/paritytech/parity-ethereum/commit/bab85dd78933edd9dde66ef67f10b36136683cd3 , most likely culprit is 
https://github.com/paritytech/parity-ethereum/commit/993650f3d63c04fe2f636bfaeeb02cfa301e3c7d
> Fix parity: 

- hive.go
- images.go
- simulator.go
This is to fix issue 122. Make the simulator able to specify a kill-timeout on containers
> Fixing Issue 122 Make the simulator able to specify a kill-timeout on containers

- hive.go
> log output folder

- simulators/ethereum/consensus/hivemodel.py
Fixes:
```
5e87dc96] Exception while starting/running node
[5e87dc96] free variable 'node' referenced before assignment in enclosing scope
[5e87dc96]  Checking version
[5e87dc96]  Checking version
[5e87dc96] Traceback (most recent call last):
[5e87dc96]   File "/hivemodel.py", line 200, in _startNodeAndRunTestWrapped
[5e87dc96]     return self._startNodeAndRunTest(testcase)
[5e87dc96]   File "/hivemodel.py", line 256, in _startNodeAndRunTest
[5e87dc96]     reportTest(testcase)
[5e87dc96]   File "/hivemodel.py", line 240, in reportTest
[5e87dc96]     node.nodeId,
[5e87dc96] NameError: free variable 'node' referenced before assignment in enclosing scope
[5e87dc96] Exception while starting/running node
[5e87dc96] free variable 'node' referenced before assignment in enclosing scope
```
> simulator: fix a free varialbe assignment

- simulator.go
Deleting the container may take a while, better to release lock before doing so
> don't do docker removal while holding lock

- clients/parity_master/parity.sh
> fix deprecation of a parity chainconfig field

- clients/parity_master/Dockerfile
Fixes https://github.com/ethereum/hive/issues/165
> parity: update cargo installation

- hive.go
- images.go
- resultview/index.html
This should address the GUI issues in 170 and 166
> Resolve issues #170 and #166

- clients/aleth_master/aleth.sh
- clients/aleth_nightly/aleth.sh
- clients/go-ethereum_master/geth.sh
- clients/go-ethereum_stable/geth.sh
- clients/parity_beta/parity.sh
- clients/parity_master/parity.sh
New updates for `ConstantinopleFix` . @gumb0 or @chfast , what's the config param for aleth ?
> update client scripts for st petersburg

- simulators/devp2p/basic/Dockerfile
> Make devp2p tests script executable

- chaintools/chaintools.go
> Dependency changed

- README.md
Adds the command lines you might want to use as a readme quickstart. 
Helps with  #196
> Added test command lines to readme

- clients/aleth/Dockerfile
- clients/aleth/aleth.sh
- clients/aleth/enode.sh
- pseudoclients/relay/relay.sh
- simulators/devp2p/udp.go
Gets the Aleth devp2p tests working
> Fix Aleth tests + remove some redundant code

- chaintools/sealingEthash.go
> Chaintools fix

- benchmarker.go
- clients/go-ethereum/geth.sh
- containers.go
- hive.go
- internal.go
- shell.go
- simulator.go
- validator.go
> Add simulator loglevel

- clients/besu/Dockerfile
- clients/besu/besu.sh
- clients/besu/enode.sh
- clients/besu/genesis.json
Adds besu to hive, including speculative names of future roadmap
upgrades based on the devcon location pattern.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
> Add Besu to Hive

- hiveviewer/Scripts/app/app.js
- hiveviewer/index.html
- hiveviewer/viewer.html
This PR implements a logfile viewer, and makes it possible to share links. e.g. https://hivetests.ethdevops.io/viewer.html?file=Results/1587575081-30af2072e5bd409461e31a3aa5e12250-simulator.log . 
It even has highlightning of selected linenumbers, kind of like github.
> hiveviewer: standalone logviewer

- simulators/ethereum/graphql/tests.sh
- simulators/ethereum/sync/sync_test.go
- simulators/ethereum/sync/tests.sh
Makes the output / test description amenable to markdown formatting
> Formatting

- simulators/ethereum/consensus/main.go
Better output for consensus tests+ better descriptions
> consensus tests: formatting + description

- clients/besu/besu.sh
> clients/besu: allow import to fail

- .gitignore
- clients/besu/besu.sh
Added flag to set min gas price so that the value matches the expected value from eth_gasPrice graphql test.
> Add min gas price startup flag to besu.sh

- clients/go-ethereum/geth.sh
Updates to geth command
TODO (some other PR): perform graphql tests against port `8545`
> clients/geth: update commandline args

- clients/besu/besu.sh
Closes https://github.com/ethereum/hive/issues/337
> clients/besu: disable secp256k1.randomize

- simulators/ethereum/sync/sync_test.go
This fixes some issues with the sync test:
- The enode URL is now fixed up by the hive controller, so the
test doesn't need to do it anymore.
- The test didn't verify the expected head block hashes on the source
and sink nodes. Now it does.
- We now use a network ID that's not mainnet because Trinity has
special handling for ID 1 and started a mainnet sync.
- The progress checker no longer uses BlockByNumber because it is
based on a batch request and not all clients support those.
> simulators/ethereum/sync: improve the sync test

- internal/libhive/api.go
This resolves a recent regression with aleth on the sync test. For some
reason, aleth returns port zero in its node URL. Since aleth is not
maintained anymore, there isn't much of a chance this will ever be fixed
upstream.
> internal/libhive: fixup client enode ports if zero

- internal/libhive/docker.go
This removes the 'privileged' flag on client containers, as well as the
SYS_PTRACE capability and seccomp exception. I think these privileges
were mostly needed for debugging, but it's definitely wrong to run the
client like that.
Also includes a change to debounce the 'checking container online...' log
message since it was now being printed every 100ms.
> internal/libhive: run clients in unprivileged containers

- cmd/hiveview/assets/app.js
- cmd/hiveview/assets/assets.go
We all know them from YouTube: links in description.
Now you can click them on Hive as well.
> cmd/hiveview: make links in description work

- simulators/smoke/network/go.mod
- simulators/smoke/network/go.sum
- simulators/smoke/network/network.go
This PR fixes the network smoke test to match the updates made to the network API.
> simulators/smoke/network: fix network smoke test

- clients/aleth/Dockerfile
- clients/besu/Dockerfile
- clients/ethereumj/Dockerfile
- clients/go-ethereum/Dockerfile
- clients/nethermind/Dockerfile
- clients/openethereum/Dockerfile
- clients/trinity/Dockerfile
- hive.go
This PR changes the way clients report their version to hive. They report to a txt file instead of a json file.
> clients: more meaningful client version reporting

- hive.go
This changes the client build to behave like the documentation says:
it's OK for some client builds to fail, and they'll just be excluded from the run.
However, at least one client must build successfully.
> hive: don't abort entire run for client build error

- cmd/hiveview/listing.go
This avoids reading and marshalling thousands of (potentially very large) files just to generate the listing
> cmd/hiveivew: make listing faster

- internal/libhive/api.go
Crashfix 
```
INFO[02-24|12:48:47] API: client aleth started                suite=0 test=96 container=b165960c
INFO[02-24|12:48:47] API: client aleth started                suite=0 test=99 container=c742b631
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 2944 [running]:
runtime.throw(0xa810de, 0x15)
/opt/go/1.14.2/src/runtime/panic.go:1116 +0x72 fp=0xc00037f628 sp=0xc00037f5f8 pc=0x435a42
runtime.mapassign_faststr(0x9ca4c0, 0xc000200e10, 0xc0002eb7c8, 0x5, 0xc000210f28)
/opt/go/1.14.2/src/runtime/map_faststr.go:291 +0x3de fp=0xc00037f690 sp=0xc00037f628 pc=0x415a8e
github.com/ethereum/hive/internal/libhive.(*simAPI).startClient(0xc000384070, 0xb4ca60, 0xc0001ca460, 0xc0001d3000)
/data/hive/internal/libhive/api.go:250 +0xff5 fp=0xc00037fa68 sp=0xc00037f690 …
```
> internal/libhive: prevent concurrent map access panic

- clients/nethermind/mapper.jq
- clients/openethereum/mapper.jq
> Berlinupdates

- clients/besu/besu.sh
> clients/besu: fix #454

- .circleci/compile-simulators.sh
- .circleci/upgrade-hivesim.sh
This also improves portability of compiler-simulators.sh
> .circleci: add script to upgrade hivesim in simulators

- docs/commandline.md
- docs/simulators.md
Describes the initial system setup in more detail.
Corrects the documentation about the simulators so that the tests pass now.
> docs: improve documentation

- simulators/ethereum/consensus/types.go
> simulators/consensus: fix json types

- hive.go
> hive: simulator development mode

- README.md
Add 'CREATE/CREATE2 with max nonce' and 'Blake2' mentions
> Update readme with Nethermind trophies

- simulators/ethereum/engine/enginetests.go
Adds test case suggested by @mkalinin:
`P <- INV_P`, `newPayload(INV_P)`, `fcU(head: P, payloadAttributes: attrs)`, `getPayload(…)`
> simulators/ethereum/engine: Build After Invalid Payload

- clients/teku-bn/Dockerfile
- clients/teku-bn/hive.yaml
- clients/teku-bn/teku_bn.sh
- clients/teku-vc/Dockerfile
- clients/teku-vc/hive.yaml
- clients/teku-vc/teku_vc.sh
> clients/teku: add Teku beacon node and validator client

- simulators/ethereum/engine/enginetests.go
Implements test cases in this PR: https://github.com/txrx-research/TestingTheMerge/pull/6
> simulators/ethereum/engine: Add Re-Org Validated Side Chain Payload Test

- clients/lighthouse-bn/Dockerfile
- clients/lighthouse-bn/lighthouse_version.sh
- clients/lighthouse-vc/Dockerfile
- clients/lighthouse-vc/lighthouse_version.sh
Add a script to pull out the Lighthouse version and store it in `version.txt`
> clients/lighthouse-bn,clients/lighthouse-vc: add version info

- simulators/ethereum/engine/synctests.go
Fixes a compilation issue in the newly introduced synctests.go
> simulators/ethereum/engine: Fix Sync Tests

- clients/nethermind/mkconfig.jq
- clients/nethermind/test.cfg
Changes Included
Add Enabled Modules explicitly to include previously disabled modules like the Debug Module (for Nethermind)
> Added debug module in enabled modules

- clients/besu/besu.sh
Signed-off-by: Gabriel-Trintinalia <gabriel.trintinalia@consensys.net>
Change sync mode to snap sync instead of fast sync
> clients/besu: change sync mode to snap sync instead of fast sync

- clients/nethermind/mapper.jq
> clients/nethermind: add shanghai EIPs to mapper

- clients/nimbus-bn/Dockerfile
- clients/nimbus-bn/nimbus_bn.sh
- clients/nimbus-bn/nimbus_version.sh
- clients/nimbus-vc/Dockerfile
- clients/nimbus-vc/nimbus_version.sh
Fix nimbus beacon node and validator client by removing compile time parameters, removing parameters from `config.yaml` and modifying some other ones.
> clients/nimbus: fix nimbus

- clients/go-ethereum/Dockerfile
Adds curl install to the Geth's docker image.
> clients/go-ethereum: re-add curl in docker

- clients/besu/mapper.jq
Add Cancun for timestamp for besu.
> clients/besu: Cancun Support.

- clients/ethereumjs/mapper.jq
Add Cancun for timestamp for `ethereumjs`.
> clients/ethereumjs: Cancun Support

- simulators/ethereum/engine/main.go
Fixes an issue when comparing genesis TTD with its difficulty.
> simulators/ethereum/engine: Fix genesis on most tests

- clients/nethermind/Dockerfile
- clients/nethermind/Dockerfile.git
- clients/nethermind/Dockerfile.local
- clients/nethermind/nethermind.sh
As we just updated the Nethermind executable name, the change should be reflected here as well to keep things working.
Also, updated the base Docker image.
> Update Nethermind executable name

- clients/nethermind/mapper.jq
Fixes according to https://github.com/ethereum/EIPs/pull/7354
> clients/nethermind: Rename blob fields in mapper

- clients/nethermind/mapper.jq
Add all Cancun EIPs to the mapper.
> clients/nethermind: add all cancun EIPs to mapper

- simulators/ethereum/pyspec/runner.go
Temporary fix to use the correct `engine_forkchoiceUpdated` version when calling the client after sending the payload.
The correct fix would be to include the version number in the fixture: https://github.com/ethereum/execution-spec-tests/issues/255
> simulators/ethereum/pyspec: Use correct ForkchoiceUpdated version

- configs/cancun.yaml
The besu team requested we switch back to tracking main
> Update besu branch back to main

- configs/cancun.yaml
> configs/cancun: Update Geth

- clients/ethereumjs/ethereumjs.sh
Fixes EthJS afer https://github.com/ethereumjs/ethereumjs-monorepo/pull/3069/
> clients/ethereumjs: Remove `transports` parameter

- simulators/ethereum/engine/helper/helper.go
Trims the logging of the round-trip requests to the client in order to not grow the log sizes too much.
> simulators/ethereum/engine: Trim log output of requests

- clients/erigon/Dockerfile.git
Fixes Erigon's `Dockerfile.git` by borrowing the changes from this PR: https://github.com/ledgerwatch/erigon/pull/8829
> clients/erigon: Fix git dockerfile

- clients/besu/Dockerfile.git
Fixes Besu's git build in `Dockerfile.git` by borrowing solution from this PR: https://github.com/hyperledger/besu/pull/6215
> clients/besu: Fix git dockerfile

- clients/reth/Dockerfile
> clients/reth: use ghcr.io/paradigmxyz/reth as base image

- .circleci/continue_config.yml
#980 had an error in the syntax in continue_config.yml
> .ciricleci: fix circleci script after breaking from #980

- simulators/eth2/engine/scenarios.go
> simulators/eth2/engine: Fix error checking

- clients/besu/mapper.jq
One liner change to fix failing tests
> clients/besu: fix merge block in mapper

- simulators/portal/history/src/suites/trin_bridge.rs
> simulators/portal/history: trin_bridge suite remove redundant extra client

- clients/shisui/Dockerfile
- clients/shisui/hive.yaml
- clients/shisui/shisui.sh
> clients/shisui: update startup script

- simulators/portal/beacon/src/suites/interop.rs
In order to test offer/gossip in the Portal beacon network, the node needs to first also do light client sync to be able to validate the offered content. This requires these test to be adjusted to provide the proper light client data first in order to be able to sync. Remove these incomplete tests for now to avoid false failures.
> simulators/portal/beacon: Remove incomplete gossip/offer tests

- clients/shisui/shisui.sh
> clients/shisui: enable nat in hive test

- hivesim-rs/Cargo.toml
the version was outdated it was blocking us updating the simulators
> hivesim-rs: bump jsonrpsee version

- simulators/portal/Cargo.lock
- simulators/portal/Cargo.toml
- simulators/portal/src/suites/history/interop.rs
- simulators/portal/src/suites/state/interop.rs
updating the test to the latest ethportal-hive version
> simulators/portal: update ethportal-api for offer update

- simulators/portal/Cargo.lock
- simulators/portal/Cargo.toml
- simulators/portal/src/suites/beacon/interop.rs
- simulators/portal/src/suites/beacon/rpc_compat.rs
- simulators/portal/src/suites/history/interop.rs
- simulators/portal/src/suites/history/rpc_compat.rs
- simulators/portal/src/suites/state/interop.rs
- simulators/portal/src/suites/state/rpc_compat.rs
@kdeme @bhartnett ping for review
I tested locally  and everything appears to be working for trin/fluffy with the updated tests
> simulators/portal: update recursive_find_content to get_content

- clients/nethermind/Dockerfile
- clients/nethermind/Dockerfile.git
- clients/nethermind/Dockerfile.local
- clients/nethermind/mkconfig.jq
- clients/nethermind/test.cfg
- Replaced the obsolete `NETHERMIND_HIVE_ENABLED` with `NETHERMIND_HIVECONFIG_ENABLED`
- Removed the obsolete `PubSubEnabled`
- Updated Docker files to .NET 9 although I'm not sure what those `.git` and `.local` files are for. Are they used?
> clients/nethermind: fix configuration settings

- clients/samba/Dockerfile
- clients/samba/hive.yaml
- clients/samba/samba.sh
A Samba folder is created with the following files:
- DockerFile
- hive.yaml
- samba.sh
> clients/samba: add samba portal network client definition

- hive.go
> hive: add workaround for too large multipart request

- cmd/hiveview/assets/lib/utils.js
> cmd/hiveview: show ms when tests take less than a second

- clients/besu/mapper.jq
- clients/erigon/mapper.jq
- clients/ethereumjs/mapper.jq
- clients/go-ethereum/mapper.jq
- clients/nethermind/mapper.jq
- clients/nimbus-el/mapper.jq
- clients/reth/mapper.jq
Makes changes according to: https://github.com/ethereum/EIPs/pull/9240
> clients: add baseFeeUpdateFraction to the genesis files

- clients/trin/Dockerfile.git
- clients/ultralight/Dockerfile.git
Adding Dockerfile.git so we can test if ping extensions work for Ultralight
> clients/ultralight: add Dockerfile support to build Ultralight from git

- clients/shisui/Dockerfile
- clients/shisui/Dockerfile.git
- clients/shisui/shisui.sh
- clients/trin/Dockerfile.git
We need to add Dockerfile.git for testing the Portal clients with Ping extensions
> clients/shisui: add Dockerfile support to build Shisui from git

- clients/trin/Dockerfile
> clients/trin: remove copying trin_version.sh

- clients/nimbus-el/Dockerfile
- clients/nimbus-el/nimbus.sh
Update the `Dockerfile` and runner `nimbus.sh` for supporting hive tests in the updated _nimbus execution client_
> clients/nimbus-el: update nimbus execution client Dockerfile

- clients/besu/mapper.jq
- clients/erigon/mapper.jq
- clients/ethereumjs/mapper.jq
- clients/go-ethereum/mapper.jq
- clients/nethermind/mapper.jq
- clients/nimbus-el/mapper.jq
- clients/reth/mapper.jq
Expand on #1229 to use variables in every client.
> clients/el: Add `HIVE_CANCUN_BLOB_*` variables

- clients/nimbus-el/Dockerfile.git
similar problem as in https://github.com/ethereum/hive/pull/1232
> clients/nimbus-el: add .git approach Dockerfile

- clients/nimbus-el/mapper.jq
- Add missing `depositContractAddress`
- Remove `terminalTotalDifficultyPassed`
- Rename `mergeForkBlock` to `mergeNetsplitBlock`
ping @advaita-saha
> clients/nimbus-el: update nimbus execution client mapper.jq

- simulators/portal/src/suites/state/interop.rs
```
ErrorObject { code: ServerError(-32099), message: "Error decoding content value: could not determine content type of 0x080000003d020000f90232a0759e27a5069535949f0a7247ebc999367dbd77964d77ed004ffc8db3d4940248a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479495222290dd7278aa3ddd389cc1e1d165cc4bafe5a01ad7b80af0c28bc1489513346d2706885be90abb07f23ca28e50482adb392d61a0410d8efe973613f9463bb25a0c71ccb52b264842f4874510d70dd748fbbeb0b6a044dbbbb92e053ec5030657cf7e854062602a7dbad7890fb43c01009d1d39faf5b9010081a101008600144d8040180c8c2840027104a0d80031c6f9028b61055022063e4556d43e84a0087802a00608378509003a83ca9cfd1420245eed68d217280b016086100945109e1bbc614b28a248a1a2d881e19700c408aa02803d30c92d02c07c811d100200ab4f05e9502102240842a0890868a80084cbc96009d3040c4d09221d83da8911054c305c6 …
```
> portal/simulators: state generate the right dummy proof for block number

- clients/nethermind/Dockerfile
- clients/nethermind/Dockerfile.git
- clients/nethermind/Dockerfile.local
> clients/nethermind: fix version parsing in dockerfiles

- simulators/portal/Cargo.lock
- simulators/portal/Cargo.toml
- simulators/portal/src/suites/history/interop.rs
- simulators/portal/src/suites/state/interop.rs
Info can be found here https://github.com/ethereum/trin/pull/1753
@morph-dev ping for review
> simulators/portal: bump ethportal-api to fix 2 year old bug with offer response

- clients/ethereumjs/Dockerfile
- clients/ethereumjs/ethereumjs.sh
This change update the ethereumjs dockerfile used in hive to pull the base image from the ethereumjs image from the official registry.
> Update ethereumjs Dockerfile

- clients/besu/mapper.jq
Add system contracts to mapper
Address https://github.com/hyperledger/besu/pull/8567
> clients/besu: add system contracts to mapper

- simulators/portal/Cargo.lock
- simulators/portal/Cargo.toml
- simulators/portal/src/suites/history/interop.rs
- simulators/portal/src/suites/state/interop.rs
tests were failing due to us changing our HeaderWithProof types so decoding/encoding them would fail
> simulators/portal: bump ethportal-api to fix state tests

- clients/ethrex/Dockerfile
- clients/ethrex/enode.sh
- clients/ethrex/ethrex.sh
- clients/ethrex/genesis.json
- clients/ethrex/mapper.jq
This PR adds support for launching with the rust execution client [ethrex](https://www.github.com/lambdaclass/ethrex).
> clients/ethrex: adding ethrex

- simulators/portal/src/suites/utils.rs
I am adding tests for Prague, we want to add a flair for prague so the new tests generated are labelled properly
> simulators/portal: add flair for prague

- hive.go
- hivesim/testapi_test.go
- internal/libhive/data.go
- internal/libhive/run.go
- internal/libhive/testmanager.go
- internal/libhive/version.go
This PR improves Hive's simulation result files by adding comprehensive run metadata that includes the Hive command, version information, and client configuration details. This improvement provides better traceability and debugging capabilities for test runs.
- **Hive Command**: Complete command-line arguments used to execute the simulation
- **Hive Version**: Comprehensive git information including commit hash, branch, dirty status, and build date
- **Client Configuration**: Full contents of `--client-file` YAML configuration (when provided)
- Automatic filtering of sensitive build arguments from result files
- Configurable exclusion list including: `GOPROXY`, `GITHUB_TOKEN`, `API_KEY`, `PASSWORD`, etc.
- Applied to both `runMetadata.clientConfig` and `HiveInfo.ClientFile`
```json
{ …
```
> feat: add runtime info like command, hive version and client config file to the simulator output

- clients/nethermind/mapper.jq
Add new EIPs to the nethermind mapper for fusaka devnet 2.
> chore(clients): update nethermind mapper for fusaka

- clients/nethermind/mapper.jq
> clients/nethermind: remove EIP-7907 from Osaka

- clients/nimbus-el/nimbus.sh
`--custom-network` has been deprecated in favor of `--network` 
https://github.com/status-im/nimbus-eth1/pull/3567
> clients/nimbus-el: change `--custom-network` to `--network`
